Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2019-06, with the labels that each got.

#122 update status even with empty configuration
  pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
Labels: size/XS

#123 reset list of tracked pods after CR removal
  pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
Labels: size/XS

#128 drop OLM deployment docs
  README.md
Labels: size/M

#124 retry Update of condition if needed
  pkg/controller/statusmanager/status_manager.go
Labels: size/M

#129 mark nmstate as experimental
  README.md
Labels: size/M

#117 test network package
  pkg/network/image-pull-policy_test.go
  pkg/network/linux-bridge_test.go
  pkg/network/multus.go
  pkg/network/multus_test.go
  pkg/network/network_test.go
  pkg/network/nmstate_test.go
  pkg/network/sriov_test.go
Labels: size/XL

#137 Added unit test for status manager
  Gopkg.lock
  Gopkg.toml
  Makefile
  pkg/controller/statusmanager/status_manager_test.go
  pkg/controller/statusmanager/statusmanager_suite_test.go
  vendor/github.com/onsi/ginkgo/ginkgo/bootstrap_command.go
  vendor/github.com/onsi/ginkgo/ginkgo/build_command.go
  vendor/github.com/onsi/ginkgo/ginkgo/convert/ginkgo_ast_nodes.go
  vendor/github.com/onsi/ginkgo/ginkgo/convert/import.go
  vendor/github.com/onsi/ginkgo/ginkgo/convert/package_rewriter.go
  vendor/github.com/onsi/ginkgo/ginkgo/convert/test_finder.go
  vendor/github.com/onsi/ginkgo/ginkgo/convert/testfile_rewriter.go
  vendor/github.com/onsi/ginkgo/ginkgo/convert/testing_t_rewriter.go
  vendor/github.com/onsi/ginkgo/ginkgo/convert_command.go
  vendor/github.com/onsi/ginkgo/ginkgo/generate_command.go
  vendor/github.com/onsi/ginkgo/ginkgo/help_command.go
  vendor/github.com/onsi/ginkgo/ginkgo/interrupthandler/interrupt_handler.go
  vendor/github.com/onsi/ginkgo/ginkgo/interrupthandler/sigquit_swallower_unix.go
  vendor/github.com/onsi/ginkgo/ginkgo/interrupthandler/sigquit_swallower_windows.go
  vendor/github.com/onsi/ginkgo/ginkgo/main.go
  vendor/github.com/onsi/ginkgo/ginkgo/nodot/nodot.go
  vendor/github.com/onsi/ginkgo/ginkgo/nodot_command.go
  vendor/github.com/onsi/ginkgo/ginkgo/notifications.go
  vendor/github.com/onsi/ginkgo/ginkgo/run_command.go
  vendor/github.com/onsi/ginkgo/ginkgo/run_watch_and_build_command_flags.go
  vendor/github.com/onsi/ginkgo/ginkgo/suite_runner.go
  vendor/github.com/onsi/ginkgo/ginkgo/testrunner/build_args.go
  vendor/github.com/onsi/ginkgo/ginkgo/testrunner/build_args_old.go
  vendor/github.com/onsi/ginkgo/ginkgo/testrunner/log_writer.go
  vendor/github.com/onsi/ginkgo/ginkgo/testrunner/run_result.go
  vendor/github.com/onsi/ginkgo/ginkgo/testrunner/test_runner.go
  vendor/github.com/onsi/ginkgo/ginkgo/testsuite/test_suite.go
  vendor/github.com/onsi/ginkgo/ginkgo/testsuite/vendor_check_go15.go
  vendor/github.com/onsi/ginkgo/ginkgo/testsuite/vendor_check_go16.go
  vendor/github.com/onsi/ginkgo/ginkgo/unfocus_command.go
  vendor/github.com/onsi/ginkgo/ginkgo/version_command.go
  vendor/github.com/onsi/ginkgo/ginkgo/watch/delta.go
  vendor/github.com/onsi/ginkgo/ginkgo/watch/delta_tracker.go
  vendor/github.com/onsi/ginkgo/ginkgo/watch/dependencies.go
  vendor/github.com/onsi/ginkgo/ginkgo/watch/package_hash.go
  vendor/github.com/onsi/ginkgo/ginkgo/watch/package_hashes.go
  vendor/github.com/onsi/ginkgo/ginkgo/watch/suite.go
  vendor/github.com/onsi/ginkgo/ginkgo/watch_command.go
Labels: size/XXL

#138 fix bridge-marker daemonset type
  data/linux-bridge/0004-bridge-marker-daemonset.yaml
Labels: size/XS

#139 fix ready condition defaulting
  pkg/controller/statusmanager/status_manager.go
Labels: size/XS

#140 set not failing only after setting progressing
  pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
  pkg/controller/statusmanager/status_manager.go
Labels: size/S

#118 Functional tests
  .gitignore
  Gopkg.lock
  Makefile
  automation/check-patch.sh
  cluster/functest.sh
  cluster/sync.sh
  test/check/check.go
  test/check/components.go
  test/check/conditions.go
  test/e2e/deployment_test.go
  test/e2e/main_test.go
  test/e2e/recovery_test.go
  test/e2e/validation_test.go
  test/operations/operations.go
  vendor/github.com/openshift/origin/LICENSE
  vendor/github.com/openshift/origin/hack/build-rpm-release.sh
  vendor/github.com/openshift/origin/pkg/security/apis/security/doc.go
  vendor/github.com/openshift/origin/pkg/security/apis/security/register.go
  vendor/github.com/openshift/origin/pkg/security/apis/security/types.go
  vendor/github.com/openshift/origin/pkg/security/apis/security/zz_generated.deepcopy.go
Labels: size/XXL

#143 Compile operator with 1.11
  build/operator/Dockerfile
Labels: size/XS

#146 Rename test to unit-test
  Makefile
Labels: size/XS

#145 Only run update logic if objects are actually different
  Gopkg.lock
  pkg/apply/apply.go
  pkg/apply/apply_test.go
  pkg/apply/merge.go
  pkg/apply/merge_test.go
  pkg/util/k8s/unstructured.go
  vendor/k8s.io/client-go/testing/actions.go
  vendor/k8s.io/client-go/testing/fake.go
  vendor/k8s.io/client-go/testing/fixture.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
Labels: do-not-merge/hold, size/XXL

#149 specify minKubeVersion in CSV
  templates/cluster-network-addons/VERSION/cluster-network-addons-operator.VERSION.clusterserviceversion.yaml.in
Labels: size/XS

#150 use IfNotPresent pull policy in examples
  pkg/components/components.go
  templates/cluster-network-addons/VERSION/cluster-network-addons-operator.VERSION.clusterserviceversion.yaml.in
Labels: size/XS

#151 fix description and category in CSV
  templates/cluster-network-addons/VERSION/cluster-network-addons-operator.VERSION.clusterserviceversion.yaml.in
Labels: size/S

#152 expose NetworkAddonsConfig CRD group in CSV
  templates/cluster-network-addons/VERSION/cluster-network-addons-operator.VERSION.clusterserviceversion.yaml.in
Labels: size/XS

#153 run tests on STD-CI without colors
  Makefile
  automation/test.sh
Labels: size/XS

#155 keep operator version as env variable
  cmd/manager/main.go
  pkg/components/components.go
  tools/manifest-templator/manifest-templator.go
Labels: size/XS

#154 drop additional manifests from bundle
  build/registry/Dockerfile
Labels: size/XS

#156 report version in Status
  pkg/apis/networkaddonsoperator/v1alpha1/networkaddonsconfig_types.go
  pkg/components/components.go
  pkg/controller/statusmanager/status_manager.go
  test/check/check.go
  test/e2e/main_test.go
  test/e2e/version_test.go
  tools/manifest-templator/manifest-templator.go
Labels: size/L

#159 don't use PullAlways in tests
  test/e2e/deployment_test.go
Labels: size/S

#161 Added missing quotes for sriov network type and name fields
  data/sriov/004-sriov-network.yaml
Labels: size/XS

#162 include KubeMacPool in functional tests
  test/e2e/deployment_test.go
Labels: size/M

#158 list images used by components in status
  pkg/apis/networkaddonsoperator/v1alpha1/networkaddonsconfig_types.go
  pkg/apis/networkaddonsoperator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
  pkg/controller/statusmanager/status_manager.go
  test/e2e/containers_test.go
Labels: size/L

#157 reference operator on deployed objects
  pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
  test/check/check.go
Labels: size/M

#163 rename test targets
  Makefile
  README.md
  automation/test.sh
  test/e2e/workflow/containers_test.go
  test/e2e/workflow/deployment_test.go
  test/e2e/workflow/main_test.go
  test/e2e/workflow/recovery_test.go
  test/e2e/workflow/validation_test.go
  test/e2e/workflow/version_test.go
Labels: size/S

#165 fix PHONY
  Makefile
Labels: size/XS

#164 add keep checking while test helper
  test/check/check.go
  test/e2e/workflow/version_test.go
Labels: size/M

#160 lifecycle test suite
  Gopkg.lock
  Makefile
  README.md
  automation/check-patch.lifecycle.k8s-1.11.0.mounts
  automation/check-patch.lifecycle.k8s-1.11.0.packages
  automation/check-patch.lifecycle.k8s-1.11.0.sh
  automation/check-patch.lifecycle.os-3.11.0.mounts
  automation/check-patch.lifecycle.os-3.11.0.packages
  automation/check-patch.lifecycle.os-3.11.0.sh
  automation/check-patch.sh
  automation/check-patch.workflow.k8s-1.11.0.mounts
  automation/check-patch.workflow.k8s-1.11.0.packages
  automation/check-patch.workflow.k8s-1.11.0.sh
  automation/check-patch.workflow.os-3.11.0.mounts
  automation/check-patch.workflow.os-3.11.0.packages
  automation/check-patch.workflow.os-3.11.0.sh
  automation/test.sh
  cluster/operator-install.sh
  cluster/operator-push.sh
  hack/release.sh
  pkg/components/components.go
  stdci.yaml
  test/check/check.go
  test/e2e/lifecycle/deployment_test.go
  test/e2e/lifecycle/main_test.go
  test/releases/0.10.0.go
  test/releases/releases.go
  vendor/github.com/blang/semver/LICENSE
  vendor/github.com/blang/semver/json.go
  vendor/github.com/blang/semver/range.go
  vendor/github.com/blang/semver/semver.go
  vendor/github.com/blang/semver/sort.go
  vendor/github.com/blang/semver/sql.go
Labels: size/XXL

#169 fix generating of release modules in release.sh
  hack/release.sh
Labels: size/XS

#170 fix generating of release modules in release.sh [2]
  hack/release.sh
Labels: size/XS

#172 fix Release sort
  test/releases/releases.go
Labels: size/XS

#171 Release 0.10.0
  Makefile
  README.md
  manifests/cluster-network-addons/0.10.0/cluster-network-addons-operator.0.10.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.10.0/namespace.yaml
  manifests/cluster-network-addons/0.10.0/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.10.0/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.10.0/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.11.0.go
Labels: size/L

#173 Refactor VERSION in Makefile
  Makefile
Labels: size/XS

#176 document bridge configuration
  README.md
Labels: size/S

#175 add upgrade tests to lifecycle suite
  test/check/check.go
  test/e2e/lifecycle/upgrade_test.go
Labels: size/L
