Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2019-11, with the labels that each got.

#252 bridge cni: always deploy cnv- prefixed binaries
  data/linux-bridge/002-linux-bridge.yaml
Labels: dco-signoff: yes, size/XS

#259 bump knmstate to 0.12.0
  pkg/components/components.go
  test/releases/0.20.0.go
Labels: dco-signoff: yes, size/XS

#258 run tests against OKD and simplify e2e automation scripts
  automation/check-patch.e2e-lifecycle-k8s.mounts
  automation/check-patch.e2e-lifecycle-k8s.packages
  automation/check-patch.e2e-lifecycle-k8s.sh
  automation/check-patch.e2e-lifecycle-okd.mounts
  automation/check-patch.e2e-lifecycle-okd.packages
  automation/check-patch.e2e-lifecycle-okd.sh
  automation/check-patch.e2e-workflow-k8s.mounts
  automation/check-patch.e2e-workflow-k8s.packages
  automation/check-patch.e2e-workflow-k8s.sh
  automation/check-patch.e2e-workflow-okd.mounts
  automation/check-patch.e2e-workflow-okd.packages
  automation/check-patch.e2e-workflow-okd.sh
  automation/check-patch.e2e.mounts
  automation/check-patch.e2e.packages
  automation/check-patch.e2e.setup.sh
  automation/check-patch.lifecycle.k8s-1.13.3.mounts
  automation/check-patch.lifecycle.k8s-1.13.3.packages
  automation/check-patch.lifecycle.k8s-1.13.3.sh
  automation/check-patch.lifecycle.os-3.11.0.mounts
  automation/check-patch.lifecycle.os-3.11.0.packages
  automation/check-patch.lifecycle.os-3.11.0.sh
  automation/check-patch.sh
  automation/check-patch.workflow.k8s-1.13.3.mounts
  automation/check-patch.workflow.k8s-1.13.3.packages
  automation/check-patch.workflow.k8s-1.13.3.sh
  automation/check-patch.workflow.os-3.11.0.mounts
  automation/check-patch.workflow.os-3.11.0.packages
  automation/check-patch.workflow.os-3.11.0.sh
  automation/test.sh
  cluster/operator-push.sh
  stdci.yaml
  test/check/check.go
  test/check/components.go
  test/e2e/workflow/deployment_test.go
  test/okd/okd.go
  test/releases/releases.go
Labels: dco-signoff: yes, size/L

#254 use minimal resource requests
  cluster/up.sh
  data/kubemacpool/003-deployment.yaml
  data/linux-bridge/0004-bridge-marker-daemonset.yaml
  data/linux-bridge/002-linux-bridge.yaml
  data/multus/002-multus.yaml
  data/nmstate/003-operator.yaml
  data/ovs/002-ovs-daemonset.yaml
Labels: dco-signoff: yes, size/M

#260 Release 0.20.0
  Makefile
  README.md
  manifests/cluster-network-addons/0.20.0/cluster-network-addons-operator.0.20.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.20.0/namespace.yaml
  manifests/cluster-network-addons/0.20.0/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.20.0/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.20.0/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.21.0.go
Labels: dco-signoff: yes, size/XL

#263 Increase nmstate-handler resources
  data/nmstate/003-operator.yaml
Labels: dco-signoff: yes, size/XS

#264 Release 0.21.0
  Makefile
  README.md
  manifests/cluster-network-addons/0.21.0/cluster-network-addons-operator.0.21.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.21.0/namespace.yaml
  manifests/cluster-network-addons/0.21.0/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.21.0/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.21.0/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.22.0.go
Labels: dco-signoff: yes, size/XL

#265 Use correct nmstate version
  manifests/cluster-network-addons/0.21.0/cluster-network-addons-operator.0.21.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.21.0/operator.yaml
Labels: dco-signoff: yes, size/S

#266 Release 0.22.0
  Makefile
  README.md
  manifests/cluster-network-addons/0.22.0/cluster-network-addons-operator.0.22.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.22.0/namespace.yaml
  manifests/cluster-network-addons/0.22.0/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.22.0/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.22.0/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.23.0.go
Labels: dco-signoff: yes, size/XL

#267 Bump ovs-cni to 0.8.0
  README.md
  data/ovs/002-ovs-daemonset.yaml
  pkg/components/components.go
  test/releases/0.23.0.go
Labels: dco-signoff: yes, size/S
