Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2019-03, with the labels that each got.

#4 remove the command from operator yaml file.
  deploy/cluster-network-addons-operator_03_deployment.yaml
Labels: size/XS

#6 Fix the cluster_sync
  cluster/sync.sh
Labels: size/XS

#5 build container images on travis
  .travis.yml
  Makefile
  README.md
  build/Dockerfile
  cluster/sync.sh
Labels: size/M

#7 fix failing travis deployment
  .travis.yml
Labels: size/S

#9 fix dockerfile
  build/Dockerfile
Labels: size/XS

#10 Handle SCC
  data/linux-bridge/001-rbac.yaml
  data/linux-bridge/002-linux-bridge.yaml
  data/multus/001-rbac.yaml
  data/multus/002-multus.yaml
  pkg/controller/networkaddonsconfig/controller.go
  pkg/network/linux-bridge.go
  pkg/network/multus.go
  pkg/network/network.go
  pkg/render/render.go
Labels: size/L

#13 Fixed build warning
  cmd/manager/main.go
Labels: size/XS

#12 automatically detect multus configuration
  README.md
  config-example.yaml
  data/multus/002-multus.yaml
  pkg/apis/networkaddonsoperator/v1alpha1/networkaddonsconfig_types.go
  pkg/network/multus.go
Labels: size/L

#17 configure ImagePullPolicy via operator CR
  Gopkg.lock
  README.md
  config-example.yaml
  data/multus/002-multus.yaml
  deploy/cluster-network-addons-operator_03_deployment.yaml
  pkg/apis/networkaddonsoperator/v1alpha1/networkaddonsconfig_types.go
  pkg/network/image-pull-policy.go
  pkg/network/linux-bridge.go
  pkg/network/multus.go
  pkg/network/network.go
Labels: size/M

#14 SR-IOV support
  README.md
  config-example.yaml
  data/sriov/000-ns.yaml
  data/sriov/001-rbac.yaml
  data/sriov/002-sriov-cni.yaml
  data/sriov/003-sriov-dp.yaml
  deploy/cluster-network-addons-operator_03_deployment.yaml
  pkg/apis/networkaddonsoperator/v1alpha1/networkaddonsconfig_types.go
  pkg/network/network.go
  pkg/network/sriov.go
Labels: size/L

#20 fix openshift client issue
  cmd/manager/main.go
Labels: size/XS
