Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2019-12, with the labels that each got.

#269 Release 0.23.0
  Makefile
  README.md
  manifests/cluster-network-addons/0.23.0/cluster-network-addons-operator.0.23.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.23.0/namespace.yaml
  manifests/cluster-network-addons/0.23.0/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.23.0/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.23.0/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.24.0.go
Labels: dco-signoff: yes, size/XL

#271 bump ovs-cni to v0.9.0
  pkg/components/components.go
  test/releases/0.24.0.go
Labels: dco-signoff: yes, size/XS

#275 add owners
  OWNERS
Labels: dco-signoff: yes, release-note-none, size/XS

#276 drop stdci.yaml to stop std-ci tests
  stdci.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#272 Release 0.24.0
  Makefile
  README.md
  manifests/cluster-network-addons/0.24.0/cluster-network-addons-operator.0.24.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.24.0/namespace.yaml
  manifests/cluster-network-addons/0.24.0/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.24.0/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.24.0/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.25.0.go
Labels: approved, dco-signoff: yes, lgtm, size/XL

#270 Handling special cases of outdated/incompatible objects during reconcile
  data/multus/002-multus.yaml
  pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
  pkg/network/multus.go
  pkg/network/network.go
  test/check/components.go
  test/releases/0.25.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#277 Keep version of used components and their version at a single yaml file
  components.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S
