Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2019-10, with the labels that each got.

#246 Custom image name in the CSV generator
  pkg/components/components.go
  tools/manifest-templator/manifest-templator.go
Labels: dco-signoff: yes, size/XS

#247 Release 0.18.0
  Makefile
  README.md
  manifests/cluster-network-addons/0.18.0/cluster-network-addons-operator.0.18.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.18.0/namespace.yaml
  manifests/cluster-network-addons/0.18.0/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.18.0/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.18.0/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.19.0.go
Labels: dco-signoff: yes, size/XL

#248 Bump kubemacpool version to v0.8.0
  pkg/components/components.go
  test/releases/0.19.0.go
Labels: dco-signoff: yes, size/XS

#249 bump nmstate to v0.10.0
  data/nmstate/003-operator.yaml
  pkg/components/components.go
  test/releases/0.19.0.go
Labels: dco-signoff: yes, size/S

#251 bump kubernetes-nmstate to 0.11.0
  pkg/components/components.go
  test/releases/0.19.0.go
Labels: dco-signoff: yes, size/XS

#250 Release 0.19.0
  Makefile
  README.md
  manifests/cluster-network-addons/0.19.0/cluster-network-addons-operator.0.19.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.19.0/namespace.yaml
  manifests/cluster-network-addons/0.19.0/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.19.0/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.19.0/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.20.0.go
Labels: dco-signoff: yes, size/XL
