Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2019-04, with the labels that each got.

#24 Fix image pull policy for sriov
  pkg/network/sriov.go
Labels: size/XS

#8 add kubemacpool to the operator
  README.md
  config-example.yaml
  data/kubemacpool/000-ns.yaml
  data/kubemacpool/001-rbac.yaml
  data/kubemacpool/002-configmap.yaml
  data/kubemacpool/003-secret.yaml
  data/kubemacpool/004-statefulset.yaml
  deploy/cluster-network-addons-operator_03_deployment.yaml
  pkg/apis/networkaddonsoperator/v1alpha1/networkaddonsconfig_types.go
  pkg/network/kubemacpool.go
  pkg/network/network.go
Labels: size/L

#25 Change the linux deployment yaml
  data/linux-bridge/002-linux-bridge.yaml
Labels: size/XS

#27 Change the linux deployment yaml
  data/linux-bridge/002-linux-bridge.yaml
Labels: size/XS

#28 Document that SR-IOV network is not created by the operator
  README.md
Labels: size/S

#31 update README with some forgotten fields
  README.md
Labels: size/XS

#40 Fix kubemacpool crash
  data/kubemacpool/001-rbac.yaml
Labels: size/S

#41 keep applied config in the same namespace as the operator
  deploy/cluster-network-addons-operator_03_deployment.yaml
  pkg/controller/networkaddonsconfig/controller.go
  pkg/controller/networkaddonsconfig/previous.go
  pkg/names/names.go
Labels: size/M

#42 Generate operator manifests including OLM objects
  Makefile
  README.md
  deploy/Dockerfile
  deploy/cluster-network-addons-operator_02_rbac.yaml
  deploy/cluster-network-addons-operator_03_deployment.yaml
  deploy/crds/network-addons-config-example.cr.yaml
  deploy/crds/network-addons-config.crd.yaml
  deploy/namespace.yaml
  deploy/olm-catalog/cluster-network-addons/0.0.0/cluster-network-addons-operator.v0.0.0.clusterserviceversion.yaml
  deploy/olm-catalog/cluster-network-addons/0.0.0/network-addons-config.crd.yaml
  deploy/olm-catalog/cluster-network-addons/cluster-network-addons.package.yaml
  deploy/operator.yaml
  hack/build-manifests.sh
  pkg/components/components.go
  templates/crds/network-addons-config-example.cr.yaml.in
  templates/crds/network-addons-config.crd.yaml.in
  templates/namespace.yaml.in
  templates/olm-catalog/cluster-network-addons/VERSION/cluster-network-addons-operator.VERSION.clusterserviceversion.yaml.in
  templates/olm-catalog/cluster-network-addons/VERSION/network-addons-config.crd.yaml.in
  templates/olm-catalog/cluster-network-addons/cluster-network-addons.package.yaml.in
  templates/operator.yaml.in
  tools/manifest-templator/manifest-templator.go
Labels: size/XXL

#29 Update NetworkAddonsConfig Status field with conditions
  README.md
  data/linux-bridge/002-linux-bridge.yaml
  data/multus/002-multus.yaml
  data/sriov/002-sriov-cni.yaml
  data/sriov/003-sriov-dp.yaml
  pkg/apis/networkaddonsoperator/v1alpha1/networkaddonsconfig_types.go
  pkg/apis/networkaddonsoperator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
  pkg/controller/networkaddonsconfig/pod_controller.go
  pkg/controller/statusmanager/status_manager.go
  pkg/network/network.go
  vendor/github.com/openshift/cluster-network-operator/pkg/controller/networkconfig/networkconfig_controller.go
Labels: do-not-merge/hold, size/XL

#45 Change KubeMacPool RBAC rule
  data/kubemacpool/001-rbac.yaml
  data/kubemacpool/004-deployment.yaml
Labels: size/XS

#49 Use kubernetes core PullPolicy for imagePullPolicy
  pkg/apis/networkaddonsoperator/v1alpha1/networkaddonsconfig_types.go
  pkg/network/image-pull-policy.go
Labels: size/S

#46 Fix local cluster manifests
  .gitignore
  Makefile
  cluster/clean.sh
  cluster/sync.sh
  config-example.yaml
  deploy/olm-catalog/cluster-network-addons/0.0.0/cluster-network-addons-operator.v0.0.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/build-manifests.sh
  pkg/components/components.go
Labels: size/M

#50 Generate macpool range
  README.md
  deploy/crds/network-addons-config-example.cr.yaml
  pkg/components/components.go
  pkg/network/kubemacpool.go
Labels: size/M

#51 Update resource limit and request
  data/kubemacpool/004-deployment.yaml
Labels: size/XS

#52 fix typos in kubemacpool README
  README.md
Labels: size/XS

#53 add label for kubemacpool namespace
  data/kubemacpool/000-ns.yaml
Labels: size/XS

#44 automation: Add STDCI
  automation/check-patch.mounts
  automation/check-patch.packages
  automation/check-patch.sh
  stdci.yaml
Labels: size/S

#54 Support OpenShift 4
  cluster/sync.sh
  data/linux-bridge/002-linux-bridge.yaml
  data/multus/002-multus.yaml
  data/sriov/002-sriov-cni.yaml
  pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
  pkg/network/cluster-info.go
  pkg/network/cni/cni.go
  pkg/network/linux-bridge.go
  pkg/network/multus.go
  pkg/network/network.go
  pkg/network/sriov.go
Labels: size/L

#58 Copy *sriov to /opt/cni/bin
  data/sriov/002-sriov-cni.yaml
Labels: size/XS

#59 Create sriov network attachment definition
  README.md
  data/sriov/002-sriov-cni.yaml
  data/sriov/004-sriov-network.yaml
  deploy/olm-catalog/cluster-network-addons/0.0.0/cluster-network-addons-operator.v0.0.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/components/components.go
  pkg/network/sriov.go
Labels: do-not-merge/hold, size/M

#60 make addons images configurable during `make manifests`
  Makefile
  deploy/olm-catalog/cluster-network-addons/0.0.0/cluster-network-addons-operator.v0.0.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/components/components.go
  tools/manifest-templator/manifest-templator.go
Labels: size/M

#64 Revisit project versioning
  .gitignore
  Makefile
  README.md
  build/operator/Dockerfile
  build/operator/bin/entrypoint
  build/operator/bin/user_setup
  build/registry/Dockerfile
  cluster/clean.sh
  cluster/sync.sh
  deploy/olm-catalog/cluster-network-addons/0.0.0/network-addons-config.crd.yaml
  hack/build-manifests.sh
  manifests/cluster-network-addons/0.3.0/cluster-network-addons-operator.v0.3.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.3.0/namespace.yaml
  manifests/cluster-network-addons/0.3.0/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.3.0/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.3.0/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  templates/cluster-network-addons/VERSION/cluster-network-addons-operator.VERSION.clusterserviceversion.yaml.in
  templates/cluster-network-addons/VERSION/namespace.yaml.in
  templates/cluster-network-addons/VERSION/network-addons-config-example.cr.yaml.in
  templates/cluster-network-addons/VERSION/network-addons-config.crd.yaml.in
  templates/cluster-network-addons/VERSION/operator.yaml.in
  templates/cluster-network-addons/cluster-network-addons.package.yaml.in
  templates/olm-catalog/cluster-network-addons/VERSION/network-addons-config.crd.yaml.in
  templates/olm-catalog/cluster-network-addons/cluster-network-addons.package.yaml.in
  tools/manifest-templator/manifest-templator.go
Labels: size/L

#69 upgrade base image packages while building images
  build/operator/Dockerfile
Labels: size/XS

#71 allow namespace adjustment during manifests build
  pkg/components/components.go
  tools/manifest-templator/manifest-templator.go
Labels: size/S

#72 release 0.4.0
  Makefile
  README.md
  manifests/cluster-network-addons/0.4.0/cluster-network-addons-operator.0.4.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.4.0/namespace.yaml
  manifests/cluster-network-addons/0.4.0/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.4.0/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.4.0/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
Labels: size/L

#74 fix deployment manifest links in readme
  README.md
Labels: size/XS

#77 status: catch a few more Progressing cases
  pkg/controller/statusmanager/status_manager.go
Labels: size/XS

#76 Call syncFailing on SetNotFailing method
  pkg/controller/statusmanager/status_manager.go
Labels: size/XS

#75 startPoolRange and endPoolRange Name changed
  README.md
  data/kubemacpool/002-configmap.yaml
  data/kubemacpool/004-deployment.yaml
  manifests/cluster-network-addons/0.3.0/cluster-network-addons-operator.v0.3.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.4.0/cluster-network-addons-operator.0.4.0.clusterserviceversion.yaml
  pkg/apis/networkaddonsoperator/v1alpha1/networkaddonsconfig_types.go
  pkg/components/components.go
  pkg/network/kubemacpool.go
  templates/cluster-network-addons/VERSION/cluster-network-addons-operator.VERSION.clusterserviceversion.yaml.in
Labels: size/M

#78 run basic functional test on STD-CI
  Makefile
  README.md
  automation/check-patch.k8s-1.11.0.mounts
  automation/check-patch.k8s-1.11.0.packages
  automation/check-patch.k8s-1.11.0.sh
  automation/check-patch.os-3.11.0.mounts
  automation/check-patch.os-3.11.0.packages
  automation/check-patch.os-3.11.0.sh
  automation/check-patch.packages
  automation/check-patch.sh
  automation/test.sh
  cluster/functest.sh
  hack/build-manifests.sh
  stdci.yaml
Labels: size/L

#83 Update the kubemacpool image to use tag v0.2.0 and not latest
  pkg/components/components.go
Labels: size/XS

#81 add helper script to make releasing easier
  README.md
  hack/release.sh
Labels: size/M

#84 update manifests in README.md during release
  README.md
  hack/release.sh
Labels: size/S

#82 release 0.5.0
  Makefile
  README.md
  manifests/cluster-network-addons/0.5.0/cluster-network-addons-operator.0.5.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.5.0/namespace.yaml
  manifests/cluster-network-addons/0.5.0/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.5.0/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.5.0/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
Labels: size/L

#88 Fix operator-sdk generate command
  .gitignore
  build/Dockerfile
Labels: size/XS

#79 Add bridge-marker manifests
  README.md
  data/linux-bridge/0004-bridge-marker-daemonset.yaml
  data/linux-bridge/003-bridge-marker-rbac.yaml
  pkg/components/components.go
  pkg/network/linux-bridge.go
  tools/manifest-templator/manifest-templator.go
Labels: size/L
