Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2019-07, with the labels that each got.

#174 Install vendor tools before using them
  Makefile
Labels: size/S

#177 Update kubernetes-nmstate to v0.3.0
  data/nmstate/001-rbac.yaml
  data/nmstate/002-crd.yaml
  data/nmstate/003-operator.yaml
  pkg/components/components.go
  pkg/network/nmstate.go
  test/check/components.go
Labels: size/L

#179 Release 0.11.0
  Makefile
  README.md
  manifests/cluster-network-addons/0.11.0/cluster-network-addons-operator.0.11.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.11.0/namespace.yaml
  manifests/cluster-network-addons/0.11.0/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.11.0/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.11.0/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.12.0.go
Labels: size/L

#148 add func-test for kubemacpool
  test/check/check.go
  test/e2e/workflow/deployment_test.go
Labels: size/M

#184 Add the fmt and vet functionality to test folder
  Makefile
Labels: size/XS

#185 Bump kubemacpool version to v0.4.0
  data/kubemacpool/003-deployment.yaml
  data/kubemacpool/003-secret.yaml
  pkg/components/components.go
  test/releases/0.12.0.go
Labels: size/S

#183 Add Ovs-cni as component
  data/ovs/000-ns.yaml
  data/ovs/001-rbac.yaml
  data/ovs/002-ovs-daemonset.yaml
  pkg/apis/networkaddonsoperator/v1alpha1/networkaddonsconfig_types.go
  pkg/apis/networkaddonsoperator/v1alpha1/zz_generated.deepcopy.go
  pkg/components/components.go
  pkg/network/network.go
  pkg/network/ovs.go
  pkg/network/ovs_test.go
  test/check/components.go
  test/e2e/workflow/deployment_test.go
  test/e2e/workflow/validation_test.go
Labels: size/L

#186 Remove kubemacpool w/a in functional test
  test/check/check.go
  test/e2e/lifecycle/deployment_test.go
  test/e2e/workflow/deployment_test.go
Labels: size/M

#192 identify OKD4 using NAO
  pkg/components/components.go
  pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
Labels: size/S

#191 Bump ovs to version v0.5.0
  data/ovs/002-ovs-daemonset.yaml
  pkg/components/components.go
Labels: size/XS

#195 Fix life cycle test
  test/e2e/lifecycle/upgrade_test.go
Labels: size/XS

#196 Add ovs documentation
  README.md
Labels: size/S

#199 Add csv-generator to operator container image
  build/operator/Dockerfile
  build/operator/bin/csv-generator
  tools/manifest-templator/manifest-templator.go
Labels: size/M
