Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2019-05, with the labels that each got.

#92 Pin components version
  pkg/components/components.go
Labels: size/XS

#93 Pin sriovdp to specific version
  pkg/components/components.go
Labels: size/XS

#95 Release 0.6.0
  Makefile
  README.md
  manifests/cluster-network-addons/0.6.0/cluster-network-addons-operator.0.6.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.6.0/namespace.yaml
  manifests/cluster-network-addons/0.6.0/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.6.0/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.6.0/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
Labels: size/L

#96 Bump kubemacpool version to v0.3.0
  pkg/components/components.go
Labels: size/XS

#97 Release 0.7.0
  Makefile
  README.md
  manifests/cluster-network-addons/0.7.0/cluster-network-addons-operator.0.7.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.7.0/namespace.yaml
  manifests/cluster-network-addons/0.7.0/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.7.0/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.7.0/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
Labels: size/L

#89 Add nmstate handler daemonset to operator
  README.md
  cluster/functest.sh
  data/nmstate/000-ns.yaml
  data/nmstate/001-rbac.yaml
  data/nmstate/002-nmstated.yaml
  pkg/apis/networkaddonsoperator/v1alpha1/networkaddonsconfig_types.go
  pkg/apis/networkaddonsoperator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/networkaddonsoperator/v1alpha1/zz_generated.defaults.go
  pkg/components/components.go
  pkg/network/network.go
  pkg/network/nmstate.go
Labels: size/L

#99 Fill kubemacpool range in the fillDefaults function
  pkg/apis/networkaddonsoperator/v1alpha1/networkaddonsconfig_types.go
  pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
  pkg/network/image-pull-policy.go
  pkg/network/kubemacpool.go
  pkg/network/network.go
Labels: size/M

#100 Return error with stack trace on renderObjects
  pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
Labels: size/XS

#105 Set NetworkManager as a requirement
  README.md
  cluster/up.sh
Labels: size/S

#104 Fix nmstate crd
  data/nmstate/002-crd.yaml
  data/nmstate/003-nmstated.yaml
Labels: size/S

#106 fix nmstate version to v0.1.0
  data/nmstate/003-nmstated.yaml
  pkg/components/components.go
Labels: size/XS

#108 update manifests templates with nmstate changes
  templates/cluster-network-addons/VERSION/cluster-network-addons-operator.VERSION.clusterserviceversion.yaml.in
Labels: size/XS

#109 increase timeout for functional tests
  cluster/functest.sh
Labels: size/XS

#107 Release 0.8.0
  Makefile
  README.md
  manifests/cluster-network-addons/0.8.0/cluster-network-addons-operator.0.8.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.8.0/namespace.yaml
  manifests/cluster-network-addons/0.8.0/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.8.0/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.8.0/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
Labels: size/L

#112 test render.go module
  pkg/render/render_suite_test.go
  pkg/render/render_test.go
  pkg/render/testdata/doc.txt
  pkg/render/testdata/multiple.yaml
  pkg/render/testdata/simple.json
  pkg/render/testdata/simple.yaml
  pkg/render/testdata/template.yaml
Labels: size/L

#111 test unstructured.go module
  pkg/util/k8s/k8s_suite_test.go
  pkg/util/k8s/unstructured_test.go
Labels: size/M

#113 Bump linux bridge to v0.8.0
  pkg/components/components.go
Labels: size/XS

#114 Bump nmstate to v0.2.0
  pkg/components/components.go
Labels: size/XS

#115 Release 0.9.0
  Makefile
  README.md
  manifests/cluster-network-addons/0.9.0/cluster-network-addons-operator.0.9.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.9.0/namespace.yaml
  manifests/cluster-network-addons/0.9.0/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.9.0/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.9.0/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
Labels: size/L

#116 test merge.go module
  pkg/apply/apply_suite_test.go
  pkg/apply/merge_test.go
Labels: size/L
