Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2019-08, with the labels that each got.

#200 increase test timeouts
  test/e2e/lifecycle/deployment_test.go
  test/e2e/lifecycle/upgrade_test.go
  test/e2e/workflow/containers_test.go
  test/e2e/workflow/deployment_test.go
  test/e2e/workflow/version_test.go
Labels: size/M

#201 Add csv-generator --dump-crds option
  tools/manifest-templator/manifest-templator.go
Labels: size/XS

#197 use unified HCO conditions
  Gopkg.lock
  README.md
  pkg/apis/networkaddonsoperator/v1alpha1/networkaddonsconfig_types.go
  pkg/apis/networkaddonsoperator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/statusmanager/status_manager.go
  pkg/controller/statusmanager/status_manager_test.go
  pkg/controller/statusmanager/statusmanager_suite_test.go
  test/check/check.go
  test/check/conditions.go
  test/e2e/lifecycle/upgrade_test.go
  test/e2e/workflow/recovery_test.go
  test/e2e/workflow/validation_test.go
  test/kubectl/kubectl.go
  test/releases/releases.go
  vendor/github.com/openshift/custom-resource-status/LICENSE
  vendor/github.com/openshift/custom-resource-status/conditions/v1/_doc.go
  vendor/github.com/openshift/custom-resource-status/conditions/v1/conditions.go
  vendor/github.com/openshift/custom-resource-status/conditions/v1/types.go
  vendor/github.com/openshift/custom-resource-status/conditions/v1/zz_generated.deepcopy.go
Labels: size/XL

#198 Report unavailable when valiadation fails
  pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
  pkg/controller/statusmanager/status_manager.go
  test/e2e/workflow/validation_test.go
Labels: size/M

#202 Bump nmstate to 0.6.0
  data/nmstate/001-rbac.yaml
  data/nmstate/002-crd.yaml
  data/nmstate/003-operator.yaml
  pkg/components/components.go
  test/check/check.go
Labels: size/M

#207 Bump ovs version to v0.6.0
  pkg/components/components.go
  templates/cluster-network-addons/VERSION/cluster-network-addons-operator.VERSION.clusterserviceversion.yaml.in
Labels: size/XS

#209 Bump linux bridge cni to version v0.8.1
  pkg/components/components.go
  test/releases/0.12.0.go
Labels: size/XS

#205 Remove sriov from the network addons operator
  Makefile
  README.md
  data/sriov/000-ns.yaml
  data/sriov/001-rbac.yaml
  data/sriov/002-sriov-cni.yaml
  data/sriov/003-sriov-dp.yaml
  data/sriov/004-sriov-network.yaml
  pkg/apis/networkaddonsoperator/v1alpha1/networkaddonsconfig_types.go
  pkg/apis/networkaddonsoperator/v1alpha1/zz_generated.deepcopy.go
  pkg/components/components.go
  pkg/network/network.go
  pkg/network/sriov.go
  pkg/network/sriov_test.go
  templates/cluster-network-addons/VERSION/cluster-network-addons-operator.VERSION.clusterserviceversion.yaml.in
  test/check/components.go
  test/e2e/workflow/deployment_test.go
  test/e2e/workflow/validation_test.go
  tools/manifest-templator/manifest-templator.go
Labels: size/XL

#210 Updating bridge-marker version to 0.2.0
  pkg/components/components.go
  test/releases/0.12.0.go
Labels: size/XS

#211 Add all the components to master release
  test/e2e/lifecycle/upgrade_test.go
  test/e2e/workflow/deployment_test.go
  test/releases/0.12.0.go
Labels: size/S
