Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2020-05, with the labels that each got.

#375 Knmstate v0.20.0
  components.yaml
  data/nmstate/001-rbac.yaml
  data/nmstate/002-crd.yaml
  data/nmstate/003-operator.yaml
  pkg/components/components.go
  pkg/network/network.go
  pkg/network/nmstate.go
  test/check/components.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#378 Release 0.36.0
  Makefile
  README.md
  manifests/cluster-network-addons/0.36.0/cluster-network-addons-operator.0.36.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.36.0/namespace.yaml
  manifests/cluster-network-addons/0.36.0/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.36.0/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.36.0/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.36.0.go
  version/description
  version/version.go
Labels: dco-signoff: yes, release-note-none, size/XL

#379 Use correct github path for github-release
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#388 status_manager: only require single ready pod for deployment
  pkg/controller/statusmanager/status_manager.go
  test/check/check.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#389 keep the order of webhooks while merging
  pkg/apply/merge.go
  pkg/apply/merge_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#390 Cover all use cases at caBundle
  pkg/apply/merge.go
  pkg/apply/merge_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#393 Ensure components objects deletion and creation at e2e tests
  test/check/check.go
  test/check/components.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#396 Add github issue/PR templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#397 Bump kubemacpool v0.13.0
  components.yaml
  data/kubemacpool/kubemacpool.yaml
  hack/components.sh
  pkg/components/components.go
  test/check/components.go
  test/e2e/workflow/deployment_test.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#387 Add KUBEVIRT_PROVIDER=external support
  README.md
  cluster/operator-push.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#400 Bump kubevirtci
  automation/check-patch.e2e-lifecycle-k8s.sh
  automation/check-patch.e2e-workflow-k8s.sh
  cluster/kubevirtci.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#384 Replace multistage with vendored go
  .dockerignore
  Makefile
  build/operator/Dockerfile
  hack/generate-manifests.sh
  hack/install-go.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#401 bump kubemacpool to v0.14.0
  components.yaml
  data/kubemacpool/kubemacpool.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#402 Release 0.38.0
  Makefile
  manifests/cluster-network-addons/0.38.0/cluster-network-addons-operator.0.38.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.38.0/namespace.yaml
  manifests/cluster-network-addons/0.38.0/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.38.0/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.38.0/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.38.0.go
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL
