Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2020-12, with the labels that each got.

#683 bump kubemacpool to v0.20.4
  components.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#682 strict-reconcile, Add strict-reconcile test
  test/e2e/workflow/deployment_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#687 [release-0.42] backport bumper commits to release-0.42 branch
  Makefile
  hack/components/bump-macvtap-cni.sh
  hack/components/bump-nmstate.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#690 ci, make timeout configurable
  Makefile
  automation/check-patch.e2e-lifecycle-k8s.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#691 Drop old releases from testing
  automation/check-patch.e2e-lifecycle-k8s.sh
  test/releases/0.16.0.go
  test/releases/0.17.0.go
  test/releases/0.19.0.go
  test/releases/0.20.0.go
  test/releases/0.21.0.go
  test/releases/0.22.0.go
  test/releases/0.24.0.go
  test/releases/0.25.0.go
  test/releases/0.26.0.go
  test/releases/0.35.0.go
  test/releases/0.40.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#688 Release 0.43.0
  Makefile
  README.md
  manifests/cluster-network-addons/0.43.0/cluster-network-addons-operator.0.43.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.43.0/namespace.yaml
  manifests/cluster-network-addons/0.43.0/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.43.0/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.43.0/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.43.0.go
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#696 bumper, add PUSH_IMAGES allow linux-bridge docker push
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#699 [release-0.42] bumper, Remove unused workflow from release_0.42 branch
  .github/workflows/component-bumper.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#700 ci, Bump provider to k8s-1.19 on ci lanes
  README.md
  automation/check-patch.e2e-lifecycle-k8s.sh
  automation/check-patch.e2e-workflow-k8s.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#698 bumper, Add quay login to bumper job
  .github/workflows/component-bumper-master.yml
  .github/workflows/component-bumper-release-0.42.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#711 dockerized yq, Pin yq to version 3.3.4
  hack/components/yaml-utils.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#710 components, Fix linux-bridge wrong tagged commit
  components.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#709 bumper, fix returning annotated tag sha on tagged update-policy
  tools/bumper/component_commands.go
  tools/bumper/component_commands_test.go
  tools/bumper/git_fakes.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#712 bump nmstate to v0.37.0
  components.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#708 bumper, Change bumper fail policy
  tools/bumper/bumper.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#716 Release 0.44.0
  Makefile
  README.md
  manifests/cluster-network-addons/0.44.0/cluster-network-addons-operator.0.44.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.44.0/namespace.yaml
  manifests/cluster-network-addons/0.44.0/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.44.0/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.44.0/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.44.0.go
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#707 Stop Using Deprecated Packages
  cmd/manager/main.go
  pkg/apis/networkaddonsoperator/v1alpha1/register.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/runtime/scheme/scheme.go
  vendor/sigs.k8s.io/controller-runtime/pkg/runtime/signals/signal.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#717 validation test, Change test look for warning events
  test/check/check.go
  test/check/events.go
  test/e2e/workflow/validation_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M
