Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2020-07, with the labels that each got.

#444 Junit report
  Makefile
  automation/check-patch.e2e-lifecycle-k8s.sh
  automation/check-patch.e2e-workflow-k8s.sh
  automation/check-patch.setup.sh
  go.mod
  go.sum
  test/e2e/lifecycle/main_test.go
  test/e2e/workflow/main_test.go
  vendor/kubevirt.io/qe-tools/LICENSE
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/junit_reporter.go
  vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
  vendor/kubevirt.io/qe-tools/pkg/polarion-xml/polarion_xml.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#436 fix version in README
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#453 Bump kubemacpool to v0.15.0
  components.yaml
  data/kubemacpool/kubemacpool.yaml
  pkg/components/components.go
  test/e2e/lifecycle/upgrade_test.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#448 Split components to sub scripts
  Makefile
  hack/components.sh
  hack/components/bump-all.sh
  hack/components/bump-knmstate.sh
  hack/components/bump-kubemacpool.sh
  hack/components/bump-macvtap.sh
  hack/components/git-utils.sh
  hack/components/yaml-utils.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#459 Add describe-all to test checks
  test/check/check.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#449 move bump-all.sh functionality to Makefile
  Makefile
  hack/components/bump-all.sh
  hack/components/bump-knmstate.sh
  hack/components/bump-kubemacpool.sh
  hack/components/bump-macvtap.sh
  hack/components/git-utils.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#464 add describe logs when components has failed to be fully removed
  test/check/check.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#465 Do not trim the version exposed in CR
  pkg/components/components.go
  pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
  pkg/util/k8s/labels.go
  pkg/util/k8s/labels_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#467 Release 0.39.3
  Makefile
  manifests/cluster-network-addons/0.39.3/cluster-network-addons-operator.0.39.3.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.39.3/namespace.yaml
  manifests/cluster-network-addons/0.39.3/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.39.3/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.39.3/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.39.3.go
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, release-note-none, size/XL

#469 Introduce `networkaddonsoperator.network.kubevirt.io/rejectOwner` annotation and drop ownership of KMP secrets
  data/kubemacpool/kubemacpool.yaml
  data/nmstate/operator.yaml
  hack/components/bump-knmstate.sh
  hack/components/bump-kubemacpool.sh
  pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
  pkg/names/names.go
  test/check/components.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#450 adding linux-bridge bump script
  Makefile
  hack/components/bump-linux-bridge.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#470 Bump KubeMacPool to v0.16.0
  components.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#472 Bump knmstate to v0.23.0
  components.yaml
  data/nmstate/role.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#473 Release 0.40.0
  Makefile
  README.md
  manifests/cluster-network-addons/0.40.0/cluster-network-addons-operator.0.40.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.40.0/namespace.yaml
  manifests/cluster-network-addons/0.40.0/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.40.0/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.40.0/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.40.0.go
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#456 Add multus bump script
  Makefile
  data/multus/001-multus.yaml
  data/multus/001-rbac.yaml
  data/multus/002-multus.yaml
  hack/components/bump-multus.sh
  hack/components/yaml-utils.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#457 Add ovs-cni bump script
  Makefile
  data/ovs/001-ovs-cni.yaml
  data/ovs/001-rbac.yaml
  hack/components/bump-knmstate.sh
  hack/components/bump-kubemacpool.sh
  hack/components/bump-macvtap.sh
  hack/components/bump-ovs-cni.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#458 Add bridge-marker bump script
  Makefile
  data/linux-bridge/0004-bridge-marker-daemonset.yaml
  data/linux-bridge/003-bridge-marker-rbac.yaml
  data/linux-bridge/003-bridge-marker.yaml
  hack/components/bump-bridge-marker.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#477 use kustomize version used on kmp
  data/kubemacpool/kubemacpool.yaml
  hack/components/bump-kubemacpool.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#475 Add kubernetes-nmstate openshift scc manifests from knmstate 0.25.0
  components.yaml
  data/nmstate/scc.yaml
  hack/components/bump-knmstate.sh
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#478 Release 0.40.1
  Makefile
  README.md
  manifests/cluster-network-addons/0.40.1/cluster-network-addons-operator.0.40.1.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.40.1/namespace.yaml
  manifests/cluster-network-addons/0.40.1/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.40.1/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.40.1/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.40.1.go
  version/description
  version/version.go
Labels: dco-signoff: yes, release-note-none, size/XL

#476 add porcelain to check for uncommitted changes
  .travis.yml
  Makefile
  hack/check.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#474 Fix test NetworkAddonsConfig shouldn't be empty when config deployed
  pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
  pkg/controller/statusmanager/status_manager.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/S

#482 Bump kmp to 0.17.0
  components.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#483 Bump kubernetes-nmstate to 0.26.0
  components.yaml
  data/nmstate/operator.yaml
  hack/components/bump-knmstate.sh
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S
