Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2020-09, with the labels that each got.

#510 add 'runAsNonRoot: true' to deployment's securityContext.
  pkg/components/components.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#522 fix ClusterServiceVersion manifest to not use deprecated version
  templates/cluster-network-addons/VERSION/cluster-network-addons-operator.VERSION.clusterserviceversion.yaml.in
  tools/manifest-templator/manifest-templator.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#533 Bump Linux Bridge CNI to v0.8.7
  components.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#520 Introduce PlacementConfiguration API
  README.md
  pkg/apis/networkaddonsoperator/shared/networkaddonsconfig_types.go
  pkg/apis/networkaddonsoperator/shared/zz_generated.deepcopy.go
  pkg/network/network.go
  pkg/network/placement_configuration.go
  pkg/network/placement_configuration_test.go
  pkg/network/self_sign_configuration_test.go
  tools/bumper/component_commands.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#526 Add PlacementConfiguration to kubeMacPool
  data/kubemacpool/kubemacpool.yaml
  go.mod
  go.sum
  hack/components/bump-kubemacpool.sh
  pkg/network/kubemacpool.go
  pkg/render/render.go
  vendor/k8s.io/helm/LICENSE
  vendor/k8s.io/helm/pkg/chartutil/capabilities.go
  vendor/k8s.io/helm/pkg/chartutil/capabilities_versions_generated.go
  vendor/k8s.io/helm/pkg/chartutil/chartfile.go
  vendor/k8s.io/helm/pkg/chartutil/create.go
  vendor/k8s.io/helm/pkg/chartutil/doc.go
  vendor/k8s.io/helm/pkg/chartutil/expand.go
  vendor/k8s.io/helm/pkg/chartutil/files.go
  vendor/k8s.io/helm/pkg/chartutil/load.go
  vendor/k8s.io/helm/pkg/chartutil/requirements.go
  vendor/k8s.io/helm/pkg/chartutil/save.go
  vendor/k8s.io/helm/pkg/chartutil/transform.go
  vendor/k8s.io/helm/pkg/chartutil/values.go
  vendor/k8s.io/helm/pkg/ignore/doc.go
  vendor/k8s.io/helm/pkg/ignore/rules.go
  vendor/k8s.io/helm/pkg/proto/hapi/chart/chart.pb.go
  vendor/k8s.io/helm/pkg/proto/hapi/chart/config.pb.go
  vendor/k8s.io/helm/pkg/proto/hapi/chart/metadata.pb.go
  vendor/k8s.io/helm/pkg/proto/hapi/chart/template.pb.go
  vendor/k8s.io/helm/pkg/proto/hapi/version/version.pb.go
  vendor/k8s.io/helm/pkg/sympath/walk.go
  vendor/k8s.io/helm/pkg/version/compatible.go
  vendor/k8s.io/helm/pkg/version/doc.go
  vendor/k8s.io/helm/pkg/version/version.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#529 Add placement configuration to ovs-cni
  data/ovs/001-ovs-cni.yaml
  hack/components/bump-ovs-cni.sh
  pkg/network/ovs.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#530 Add placement configuration to multus
  data/multus/001-multus.yaml
  hack/components/bump-multus.sh
  pkg/network/multus.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#532 Add PlacementConfiguration for linux-bridge
  data/linux-bridge/002-linux-bridge.yaml
  pkg/network/linux-bridge.go
  pkg/network/network_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#531 Add placement configuration to bridge-marker
  data/linux-bridge/003-bridge-marker.yaml
  hack/components/bump-bridge-marker.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#515 Add events to status manager and controller
  README.md
  pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
  pkg/controller/networkaddonsconfig/pod_controller.go
  pkg/controller/statusmanager/status_manager.go
  pkg/eventemitter/eventemitter.go
  test/check/check.go
  test/check/events.go
  test/e2e/workflow/deployment_test.go
  test/e2e/workflow/recovery_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#536 Add Placement for knmstate
  components.yaml
  data/nmstate/operator.yaml
  hack/components/bump-knmstate.sh
  pkg/components/components.go
  pkg/network/nmstate.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#538 change kubemacpool vms to opt-in
  data/kubemacpool/kubemacpool.yaml
  hack/components/bump-kubemacpool.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#535 Add PlacementConfiguration for macvtap
  components.yaml
  data/macvtap/002-macvtap-daemonset.yaml
  hack/components/bump-macvtap.sh
  pkg/components/components.go
  pkg/network/macvtap.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#541 Release 0.42.0
  Makefile
  README.md
  manifests/cluster-network-addons/0.42.0/cluster-network-addons-operator.0.42.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.42.0/namespace.yaml
  manifests/cluster-network-addons/0.42.0/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.42.0/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.42.0/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.42.0.go
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#539 events: fix typo in available event
  pkg/eventemitter/eventemitter.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#547 events, event-emitter: change emitter to emit only for config
  pkg/eventemitter/eventemitter.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#549 Add Ram to approvers, Alon with Radim to reviewers
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#543 Bump NAC version advertised in the README
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#548 Fix missing prefix 'v' for versions v0.41.0 and v0.42.0
  hack/prepare-release.sh
  manifests/cluster-network-addons/0.41.0/cluster-network-addons-operator.0.41.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.42.0/cluster-network-addons-operator.0.42.0.clusterserviceversion.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#551 Check cnao pod restarts in CI tests
  test/check/check.go
  test/e2e/workflow/main_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#546 test: Ensure NAC does not exists eventually after delete
  test/operations/operations.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#558 Fix release 0.41.0 manifest
  manifests/cluster-network-addons/0.41.0/cluster-network-addons-operator.0.41.0.clusterserviceversion.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#555 Fix release v0.42.0 operator manifest
  manifests/cluster-network-addons/0.42.0/operator.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#542 Bump ovs-cni to v0.13.0
  components.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#563 Release 0.42.1
  Makefile
  manifests/cluster-network-addons/0.42.1/cluster-network-addons-operator.0.42.1.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.42.1/namespace.yaml
  manifests/cluster-network-addons/0.42.1/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.42.1/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.42.1/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.42.1.go
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#565 bump kubemacpool to v0.20.2
  components.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#566 Change config to use unstructured
  test/e2e/lifecycle/deployment_test.go
  test/e2e/lifecycle/main_test.go
  test/e2e/lifecycle/upgrade_test.go
  test/e2e/workflow/containers_test.go
  test/e2e/workflow/deployment_test.go
  test/e2e/workflow/main_test.go
  test/e2e/workflow/recovery_test.go
  test/e2e/workflow/validation_test.go
  test/e2e/workflow/version_test.go
  test/operations/operations.go
  test/releases/releases.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#570 change check.go api to unstructured
  test/check/check.go
  test/e2e/lifecycle/deployment_test.go
  test/e2e/lifecycle/upgrade_test.go
  test/e2e/workflow/containers_test.go
  test/e2e/workflow/deployment_test.go
  test/e2e/workflow/recovery_test.go
  test/e2e/workflow/validation_test.go
  test/e2e/workflow/version_test.go
  test/operations/operations.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#573 refactor fix of flaky validation test
  test/e2e/workflow/validation_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#537 bump CustomResourceDefinition to v1
  pkg/components/components.go
  tools/manifest-templator/manifest-templator.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#574 [release-0.42] refactor fix of flaky validation test
  test/e2e/workflow/validation_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#567 skip KMP opt-mode tests not maching CNAO config
  automation/check-patch.e2e-kubemacpool-functests.sh
  pkg/components/components.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#576 Bump macvtap-cni to v0.4.0
  components.yaml
  pkg/components/components.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#579 [release-0.42] skip KMP opt-mode tests not maching CNAO config
  automation/check-patch.e2e-kubemacpool-functests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#578 Bump bridge-marker to v0.4.0
  components.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#580 fix AddToScheme to add all served versions
  pkg/apis/addtoscheme_networkaddonsoperator_v1.go
  pkg/apis/addtoscheme_networkaddonsoperator_v1alpha1.go
  pkg/apis/apis.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#584 Release 0.42.2
  Makefile
  README.md
  manifests/cluster-network-addons/0.42.2/cluster-network-addons-operator.0.42.2.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.42.2/namespace.yaml
  manifests/cluster-network-addons/0.42.2/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.42.2/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.42.2/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.42.2.go
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL
