Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2020-11, with the labels that each got.

#640 crd, Fix placementConfiguration validation schema
  pkg/components/components.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#635 fix cluster scripts
  automation/components-functests.setup.sh
  cluster/cli.sh
  cluster/cluster.sh
  cluster/down.sh
  cluster/kubectl.sh
  cluster/kubevirtci.sh
  cluster/ssh.sh
  cluster/up.sh
  hack/bump-kubevirtci.sh
  hack/functest.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#639 [release-0.42] placement-configuration, Allow day2 changes
  pkg/network/network.go
  pkg/network/placement_configuration.go
  pkg/network/placement_configuration_test.go
  test/check/check.go
  test/e2e/workflow/deployment_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#641 Allow day2 placement config changes
  pkg/network/network.go
  pkg/network/placement_configuration.go
  pkg/network/placement_configuration_test.go
  test/check/check.go
  test/e2e/workflow/deployment_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#504 tier1, add ovs-cni e2e-functests script
  automation/check-patch.e2e-ovs-cni-functests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#633 tier1, Add bridge-marker tier1 automation test
  automation/check-patch.e2e-bridge-marker-functests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#642 Release 0.42.3
  Makefile
  manifests/cluster-network-addons/0.42.3/cluster-network-addons-operator.0.42.3.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.42.3/namespace.yaml
  manifests/cluster-network-addons/0.42.3/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.42.3/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.42.3/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.42.3.go
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#637 bumper, Add local git rebase action in bumper gitAction Job
  .github/workflows/component-bumper.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#631 tier1, Add multus tier1 automation test
  automation/check-patch.e2e-multus-functests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#644 bump bridge-marker to 0.5.0
  components.yaml
  data/linux-bridge/003-bridge-marker.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#645 bump ovs-cni to v0.15.0
  components.yaml
  data/ovs/001-ovs-cni.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#634 tier1, Add kubernetes nmstate tier1 automation test
  automation/check-patch.e2e-nmstate-functests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#646 bumper, Fix macvtap bump script name
  Makefile
  hack/components/bump-macvtap-cni.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#638 tier1, Add macvtap tier1 automation test
  automation/check-patch.e2e-macvtap-cni-functests.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#649 bump ovs-cni to v0.15.1
  components.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note, size/S

#648 bumper, Make base-branch configurable
  .github/workflows/component-bumper.yml
  tools/bumper/README.md
  tools/bumper/bumper.go
  tools/bumper/cnao_repo_commands.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#654 Revert "bumper, Make base-branch configurable (#648)"
  .github/workflows/component-bumper.yml
  tools/bumper/README.md
  tools/bumper/bumper.go
  tools/bumper/cnao_repo_commands.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#656 Bumper make base-branch configurable
  .github/workflows/component-bumper.yml
  tools/bumper/README.md
  tools/bumper/bumper.go
  tools/bumper/cnao_repo_commands.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#660 bump macvtap-cni to v0.4.2
  components.yaml
  pkg/components/components.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#662 [release-0.42] bumper, Backport bumper to release-0.42
  .github/workflows/component-bumper.yml
  components.yaml
  tools/bumper/README.md
  tools/bumper/bumper.go
  tools/bumper/bumper_test.go
  tools/bumper/cnao_repo_commands.go
  tools/bumper/cnao_repo_commands_test.go
  tools/bumper/component_commands.go
  tools/bumper/component_commands_test.go
  tools/bumper/git_fakes.go
  tools/bumper/parser.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#664 bumper, move from deprecated set-env function
  .github/workflows/component-bumper.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#661 bump ovs-cni to v0.16.2
  components.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#666 Bump kubernetes-nmstate to v0.31.1
  components.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#665 delete objects, Fix tracking of already removed objects
  pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
  test/check/check.go
  test/e2e/workflow/recovery_test.go
  test/e2e/workflow/validation_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#671 bumper, fix githubAction job env vars
  .github/workflows/component-bumper-master.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#670 bump kubemacpool to v0.20.3
  components.yaml
  data/kubemacpool/kubemacpool.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#673 bump-knmstate, update nmstate bump script crds
  hack/components/bump-nmstate.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#676 bumper, add support of deleted files
  tools/bumper/cnao_repo_commands.go
  tools/bumper/cnao_repo_commands_test.go
  tools/bumper/git_fakes.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#652 bumper, Remove Draft flag from bumper generated PRs
  tools/bumper/cnao_repo_commands.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#667 Release 0.42.4
  Makefile
  manifests/cluster-network-addons/0.42.4/cluster-network-addons-operator.0.42.4.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.42.4/namespace.yaml
  manifests/cluster-network-addons/0.42.4/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.42.4/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.42.4/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.42.4.go
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#658 placement-configurqation, update README.md
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#678 Use prow to push container at release
  .travis.yml
  hack/release.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#674 bumper, Add bumper githubAction job for release-0.42 branch
  .github/workflows/component-bumper-release-0.42.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S
