Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2020-08, with the labels that each got.

#485 Check SetFromPods has current networkAddonsConfig generation
  pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
  pkg/controller/statusmanager/status_manager.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#486 Fix reset patch version when bumping minor
  hack/bump-version.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#487 Bump kubemacpool to v0.18.0
  components.yaml
  data/kubemacpool/kubemacpool.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#439 test upgrades from 0.27.7 instead of 0.27.0
  automation/check-patch.e2e-lifecycle-k8s.sh
  manifests/cluster-network-addons/0.27.7/cluster-network-addons-operator.0.27.7.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.27.7/namespace.yaml
  manifests/cluster-network-addons/0.27.7/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.27.7/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.27.7/operator.yaml
  test/releases/0.27.7.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#488 Test upgrades from 0.39.3 instead of 0.39.0
  automation/check-patch.e2e-lifecycle-k8s.sh
  manifests/cluster-network-addons/0.39.3/cluster-network-addons-operator.0.39.3.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.39.3/namespace.yaml
  manifests/cluster-network-addons/0.39.3/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.39.3/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.39.3/operator.yaml
  test/releases/0.39.3.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#489 Delete unused OKD automation scripts
  automation/check-patch.e2e-lifecycle-okd.sh
  automation/check-patch.e2e-workflow-okd.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#492 Fix test should set targetVersion and operatorVersion
  test/e2e/workflow/version_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#408 Automation: KubeMacPool functests on CNAO lane
  automation/check-patch.e2e-kubemacpool-functests.sh
  automation/check-patch.setup.sh
  automation/components-functests.setup.sh
  hack/deploy-kubevirt.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#490 Add kmp certificates knobs to CRD
  Makefile
  README.md
  data/kubemacpool/kubemacpool.yaml
  hack/components/bump-kubemacpool.sh
  pkg/apis/networkaddonsoperator/v1alpha1/networkaddonsconfig_types.go
  pkg/apis/networkaddonsoperator/v1alpha1/zz_generated.deepcopy.go
  pkg/network/kubemacpool.go
  pkg/network/kubemacpool_test.go
  pkg/network/network.go
  pkg/network/self_sign_configuration.go
  pkg/network/self_sign_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#495 Convert the rest of the SelfSignedConfiguration test to table
  pkg/network/self_sign_configuration_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#497 Bump KubeMacPool to v0.14.6
  components.yaml
  data/kubemacpool/kubemacpool.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#499 Bump KubeMacPool to v0.19.0
  components.yaml
  data/kubemacpool/kubemacpool.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#498 Release 0.39.4
  Makefile
  manifests/cluster-network-addons/0.39.4/cluster-network-addons-operator.0.39.4.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.39.4/namespace.yaml
  manifests/cluster-network-addons/0.39.4/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.39.4/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.39.4/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.39.4.go
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#500 Release 0.41.0
  Makefile
  README.md
  manifests/cluster-network-addons/0.41.0/cluster-network-addons-operator.0.41.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.41.0/namespace.yaml
  manifests/cluster-network-addons/0.41.0/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.41.0/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.41.0/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.41.0.go
  version/description
  version/version.go
Labels: dco-signoff: yes, release-note-none, size/XL

#501 Prefix version tag with "v"
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#505 add stdout to git-clone process in bumper script
  tools/bumper/component_commands.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#513 Bump kubernetes-nmstate to v0.29.0
  components.yaml
  data/nmstate/operator.yaml
  pkg/components/components.go
  pkg/network/nmstate.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#514 Knmstate configure cert env vars
  README.md
  pkg/network/nmstate.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#518 Use image digests instead of tags
  hack/components/bump-bridge-marker.sh
  hack/components/bump-knmstate.sh
  hack/components/bump-kubemacpool.sh
  hack/components/bump-linux-bridge.sh
  hack/components/bump-macvtap.sh
  hack/components/bump-multus.sh
  hack/components/bump-ovs-cni.sh
  hack/components/docker-utils.sh
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#519 Add the relatedImages field to the CSV
  pkg/components/components.go
  pkg/components/components_suite_test.go
  pkg/components/components_test.go
  templates/cluster-network-addons/VERSION/cluster-network-addons-operator.VERSION.clusterserviceversion.yaml.in
  tools/manifest-templator/manifest-templator.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#521 Bump kubemacpool to v0.20.0
  components.yaml
  data/kubemacpool/kubemacpool.yaml
  hack/components/bump-kubemacpool.sh
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M
