Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2020-10, with the labels that each got.

#586 Typo fix in README
  README.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/XS

#585 Fix manifest link versioning in README.md
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#507 Add isPrAlreadyOpen method
  tools/bumper/bumper.go
  tools/bumper/bumper_test.go
  tools/bumper/component_commands.go
  tools/bumper/component_commands_test.go
  tools/bumper/git_fakes.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#591 bumper, Adapt nmstate bump script to comply with components.yaml name
  Makefile
  hack/components/bump-nmstate.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#569 Change upgrade test
  test/e2e/lifecycle/deployment_test.go
  test/e2e/lifecycle/upgrade_test.go
  test/releases/0.16.0.go
  test/releases/0.17.0.go
  test/releases/0.18.0.go
  test/releases/0.19.0.go
  test/releases/0.20.0.go
  test/releases/0.21.0.go
  test/releases/0.22.0.go
  test/releases/0.23.0.go
  test/releases/0.24.0.go
  test/releases/0.25.0.go
  test/releases/0.26.0.go
  test/releases/0.27.7.go
  test/releases/0.28.0.go
  test/releases/0.29.0.go
  test/releases/0.30.0.go
  test/releases/0.31.0.go
  test/releases/0.32.0.go
  test/releases/0.33.0.go
  test/releases/0.34.0.go
  test/releases/0.35.0.go
  test/releases/0.35.1.go
  test/releases/0.36.0.go
  test/releases/0.38.0.go
  test/releases/0.39.3.go
  test/releases/0.40.0.go
  test/releases/0.40.1.go
  test/releases/0.41.0.go
  test/releases/0.42.0.go
  test/releases/99.0.0.go
  test/releases/releases.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#592 bumper, Add bumper make target
  Makefile
  tools/bumper/README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#588 bumper, Fix update of component in components.yaml
  components.yaml
  tools/bumper/bumper.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#596 specialCleanUp, Fix reset cause by []error{nil}
  pkg/network/multus.go
  pkg/network/network.go
  pkg/network/nmstate.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#583 Ignore .idea/ folder created by Goland IDE
  .gitignore
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#594 bumper, Add stdout to exec output
  tools/bumper/bumper.go
  tools/bumper/parser.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#587 crdCleanUp, Cleaning release after upgrade test
  test/releases/0.16.0.go
  test/releases/0.17.0.go
  test/releases/0.18.0.go
  test/releases/0.19.0.go
  test/releases/0.20.0.go
  test/releases/0.21.0.go
  test/releases/0.22.0.go
  test/releases/0.23.0.go
  test/releases/0.24.0.go
  test/releases/0.25.0.go
  test/releases/0.26.0.go
  test/releases/0.27.7.go
  test/releases/0.28.0.go
  test/releases/0.29.0.go
  test/releases/0.30.0.go
  test/releases/0.31.0.go
  test/releases/0.32.0.go
  test/releases/0.33.0.go
  test/releases/0.34.0.go
  test/releases/0.35.0.go
  test/releases/0.35.1.go
  test/releases/0.36.0.go
  test/releases/0.38.0.go
  test/releases/0.39.3.go
  test/releases/0.40.0.go
  test/releases/0.40.1.go
  test/releases/0.41.0.go
  test/releases/0.42.0.go
  test/releases/99.0.0.go
  test/releases/releases.go
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/L

#593 validation test, Fix flaky in It("should remain at Available condition")
  test/e2e/workflow/validation_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#611 bumper, Fix flaky in bumper unit test
  tools/bumper/git_fakes.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#575 Bump kubernetes-nmstate component to v0.32.0
  components.yaml
  data/nmstate/nmstate.io_nodenetworkconfigurationenactments_crd.yaml
  data/nmstate/nmstate.io_nodenetworkconfigurationpolicies_crd.yaml
  data/nmstate/nmstate.io_nodenetworkstates_crd.yaml
  data/nmstate/operator.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#616 bumper, Add bumping repo instance
  tools/bumper/README.md
  tools/bumper/bumper.go
  tools/bumper/cnao_repo_commands.go
  tools/bumper/cnao_repo_commands_test.go
  tools/bumper/component_commands.go
  tools/bumper/component_commands_test.go
  tools/bumper/git_fakes.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#617 bumper, Add resetRepoInAllowedList to remove bump outputs
  tools/bumper/bumper.go
  tools/bumper/cnao_repo_commands.go
  tools/bumper/cnao_repo_commands_test.go
  tools/bumper/git_fakes.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#620 Bump multus to v3.4.2
  components.yaml
  data/multus/001-multus.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#622 pin multus to 3.4.2 since latest version breaks CNAO
  components.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#524 make it possible to run `kubectl explain crd`
  pkg/apis/networkaddonsoperator/shared/networkaddonsconfig_types.go
  pkg/apis/networkaddonsoperator/v1/networkaddonsconfig_types.go
  pkg/apis/networkaddonsoperator/v1alpha1/networkaddonsconfig_types.go
  pkg/components/components.go
  test/check/check.go
  test/e2e/lifecycle/upgrade_test.go
  tools/manifest-templator/manifest-templator.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#619 bumper, Add collectModifiedToTreeList to collect bump files
  tools/bumper/bumper.go
  tools/bumper/cnao_repo_commands.go
  tools/bumper/cnao_repo_commands_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#509 bumper, Add githubApi functions to open PR
  tools/bumper/bumper.go
  tools/bumper/cnao_repo_commands.go
  tools/bumper/cnao_repo_commands_test.go
  tools/bumper/component_commands.go
  tools/bumper/git_fakes.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#624 Create component-bumper.yml
  .github/workflows/component-bumper.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#625 bumper, Add go install make target dependency to auto-bumper in Makefile
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#630 readme, Remove openshift remarks from CNAO repo
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#629 bumper, Remove unsupported command from bumper script
  tools/bumper/component_commands.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#628 add linux-bridge pod description
  data/linux-bridge/002-linux-bridge.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#627 add pod description to CNAO pod
  pkg/components/components.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS
