Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2020-01, with the labels that each got.

#279 bump knmstate to v0.13.0
  components.yaml
  data/nmstate/001-rbac.yaml
  data/nmstate/002-crd.yaml
  pkg/components/components.go
  test/releases/0.25.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#280 Release 0.25.0
  Makefile
  README.md
  manifests/cluster-network-addons/0.25.0/cluster-network-addons-operator.0.25.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.25.0/namespace.yaml
  manifests/cluster-network-addons/0.25.0/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.25.0/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.25.0/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.26.0.go
Labels: approved, dco-signoff: yes, do-not-merge/hold, release-note-none, size/XL

#281 pin specific commits in components
  components.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#284 Fix warning by adding comment to exported function
  pkg/controller/networkaddonsconfig/pod_controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#283 bump to k8s 1.17
  Makefile
  automation/check-patch.e2e-lifecycle-k8s.sh
  automation/check-patch.e2e-workflow-k8s.sh
  cluster/kubevirtci.sh
  test/check/check.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#282 add script for kubemacpool bump
  .gitignore
  Makefile
  data/kubemacpool/000-ns.yaml
  data/kubemacpool/001-rbac.yaml
  data/kubemacpool/002-configmap.yaml
  data/kubemacpool/003-deployment.yaml
  data/kubemacpool/004-pod_disruption_budget.yaml
  data/kubemacpool/kubemacpool.yaml
  hack/components.sh
Labels: dco-signoff: yes, release-note-none, size/XL
