Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2021-07, with the labels that each got.

#920 resources, Update multus resources section
  data/multus/001-multus.yaml
  hack/components/bump-multus.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#922 resources, Update linux bridge minimum resources request
  data/linux-bridge/002-linux-bridge.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#921 resources, Update minimum resources request
  pkg/components/components.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#924 resources, Update multus resources section
  data/multus/001-multus.yaml
  hack/components/bump-multus.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#926 resources, Update minimum resources request
  pkg/components/components.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#925 linux bridge, Update linux bridge minimum resources request
  data/linux-bridge/002-linux-bridge.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#923 update default provider to k8s 1.21
  README.md
  automation/check-patch.e2e-lifecycle-k8s.sh
  automation/check-patch.e2e-workflow-k8s.sh
  automation/components-functests.setup.sh
  cluster/cluster.sh
  cluster/up.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#929 [Release-0.53] resources, Update minimum resources request
  data/linux-bridge/002-linux-bridge.yaml
  data/multus/001-multus.yaml
  hack/components/bump-multus.sh
  pkg/components/components.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#932 [release-0.53] macvtap, Bump to v0.5.1
  components.yaml
  data/macvtap/002-macvtap-daemonset.yaml
  pkg/components/components.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#939 Release 0.53.6
  Makefile
  README.md
  manifests/cluster-network-addons/0.53.6/cluster-network-addons-operator.0.53.6.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.53.6/namespace.yaml
  manifests/cluster-network-addons/0.53.6/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.53.6/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.53.6/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.53.6.go
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#940 fix make fmt outputs
  pkg/apis/networkaddonsoperator/shared/networkaddonsconfig_types.go
  tools/bumper/bumper.go
  tools/bumper/git_fakes.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#942 checkForDeployment, don't check on CNAO operator itself
  test/check/check.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#943 main, Update deprecated AddToScheme function
  cmd/manager/main.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#946 hack/components: Support build on SELinux enabled platforms
  hack/components/yaml-utils.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS
