Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2021-06, with the labels that each got.

#863 ci, Bump deprecated MutatingWebhookConfiguration to v1 in check test
  test/check/check.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#867 Release 0.55.0
  Makefile
  README.md
  manifests/cluster-network-addons/0.55.0/cluster-network-addons-operator.0.55.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.55.0/namespace.yaml
  manifests/cluster-network-addons/0.55.0/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.55.0/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.55.0/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.55.0.go
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#869 Release 0.53.2
  Makefile
  README.md
  manifests/cluster-network-addons/0.53.2/cluster-network-addons-operator.0.53.2.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.53.2/namespace.yaml
  manifests/cluster-network-addons/0.53.2/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.53.2/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.53.2/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.53.2.go
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#874 Release 0.44.5
  Makefile
  README.md
  manifests/cluster-network-addons/0.44.5/cluster-network-addons-operator.0.44.5.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.44.5/namespace.yaml
  manifests/cluster-network-addons/0.44.5/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.44.5/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.44.5/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.44.5.go
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#876 Change ovs-cni repo to k8snetworkplumbinggw
  components.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#878 [release-0.53] Change ovs-cni repo to k8snetworkplumbing
  components.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#877 [release-0.42] Change ovs-cni repo to k8snetworkplumbing
  components.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#846 Add relationship labels to all directly deployed components
  pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
  pkg/controller/networkaddonsconfig/networkaddonsconfig_controller_suite_test.go
  pkg/controller/networkaddonsconfig/networkaddonsconfig_controller_test.go
  pkg/controller/networkaddonsconfig/testdata/data.yaml
  pkg/names/names.go
  test/check/check.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#879 Release 0.53.3
  Makefile
  README.md
  manifests/cluster-network-addons/0.53.3/cluster-network-addons-operator.0.53.3.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.53.3/namespace.yaml
  manifests/cluster-network-addons/0.53.3/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.53.3/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.53.3/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.53.3.go
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#880 Release 0.56.0
  Makefile
  README.md
  manifests/cluster-network-addons/0.56.0/cluster-network-addons-operator.0.56.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.56.0/namespace.yaml
  manifests/cluster-network-addons/0.56.0/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.56.0/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.56.0/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.56.0.go
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#882 Follow bridge-marker's renamed branch
  components.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#883 Follow the renamed branch of OVS CNI
  components.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#886 [0.42] Follow main branch in bridge marker
  components.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#884 [0.53] Follow main branches on marker and ovs cni
  components.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#885 [0.44] Follow main branch on marker and ovs cni
  components.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#888 components, Update kubemacpool branch to main
  components.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#889 release-0.53: bump nmstate to 0.47.1
  components.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/S

#892 Release 0.53.4
  Makefile
  README.md
  manifests/cluster-network-addons/0.53.4/cluster-network-addons-operator.0.53.4.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.53.4/namespace.yaml
  manifests/cluster-network-addons/0.53.4/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.53.4/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.53.4/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.53.4.go
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#895 linux-bridge, Add Priority class
  data/linux-bridge/002-linux-bridge.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#898 multus, Add Priority class
  data/multus/001-multus.yaml
  hack/components/bump-multus.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#893 operator, Add Priority class
  pkg/components/components.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#902 components, Update multus repo url
  components.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#905 Release 0.57.0
  Makefile
  README.md
  manifests/cluster-network-addons/0.57.0/cluster-network-addons-operator.0.57.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.57.0/namespace.yaml
  manifests/cluster-network-addons/0.57.0/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.57.0/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.57.0/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.57.0.go
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#906 [release-0.42] components, Update multus repo url
  components.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#910 bumper, update default branch workflow
  .github/workflows/component-bumper-main.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#912 release-0.53, Update k8s-nmstate to use tagged policy
  components.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#913 macvtap, release-0.53, Bump to version 0.5.0
  components.yaml
  data/macvtap/002-macvtap-daemonset.yaml
  pkg/components/components.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#915 bridge-marker, release-0.53, Set source as tagged
  components.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#917 ovs-cni, release-0.53, Set source as tagged
  components.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#919 Release 0.53.5
  Makefile
  README.md
  manifests/cluster-network-addons/0.53.5/cluster-network-addons-operator.0.53.5.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.53.5/namespace.yaml
  manifests/cluster-network-addons/0.53.5/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.53.5/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.53.5/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.53.5.go
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL
