Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2021-03, with the labels that each got.

#795 certs, Add cert defaults to kubemacpool's bump script and manifest
  automation/check-patch.e2e-lifecycle-k8s.sh
  data/kubemacpool/kubemacpool.yaml
  hack/components/bump-kubemacpool.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#796 ci, Add pod status to fail test logs
  test/check/check.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#798 lifecycle, ci, Update versions tested on lifecycle ci
  automation/check-patch.e2e-lifecycle-k8s.sh
  manifests/cluster-network-addons/0.44.3/cluster-network-addons-operator.0.44.3.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.44.3/namespace.yaml
  manifests/cluster-network-addons/0.44.3/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.44.3/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.44.3/operator.yaml
  test/releases/0.29.0.go
  test/releases/0.30.0.go
  test/releases/0.31.0.go
  test/releases/0.32.0.go
  test/releases/0.33.0.go
  test/releases/0.34.0.go
  test/releases/0.35.1.go
  test/releases/0.36.0.go
  test/releases/0.38.0.go
  test/releases/0.40.1.go
  test/releases/0.41.0.go
  test/releases/0.43.0.go
  test/releases/0.44.3.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#799 Release 0.48.0
  Makefile
  README.md
  manifests/cluster-network-addons/0.48.0/cluster-network-addons-operator.0.48.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.48.0/namespace.yaml
  manifests/cluster-network-addons/0.48.0/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.48.0/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.48.0/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.48.0.go
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#801 Skip secret leftover check if not needed
  test/check/check.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#803 Remove Secret leftover checks at lifecycle test
  test/check/check.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#659 Clarify general purpose of Infra and Workload categories
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#804 Release 0.49.0
  Makefile
  README.md
  automation/check-patch.e2e-lifecycle-k8s.sh
  manifests/cluster-network-addons/0.49.0/cluster-network-addons-operator.0.49.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.49.0/namespace.yaml
  manifests/cluster-network-addons/0.49.0/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.49.0/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.49.0/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.46.0.go
  test/releases/0.49.0.go
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#805 gitActions, Restrict bumper workflows only to non-fork repo
  .github/workflows/component-bumper-master.yml
  .github/workflows/component-bumper-release-0.42.yml
  .github/workflows/component-bumper-release-0.44.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#808 Allow self sign config modification
  pkg/network/network.go
  pkg/network/self_sign_configuration.go
  pkg/network/self_sign_configuration_test.go
  test/check/check.go
  test/e2e/workflow/deployment_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#809 Release 0.50.0
  Makefile
  README.md
  manifests/cluster-network-addons/0.50.0/cluster-network-addons-operator.0.50.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.50.0/namespace.yaml
  manifests/cluster-network-addons/0.50.0/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.50.0/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.50.0/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.50.0.go
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL
