Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2021-01, with the labels that each got.

#729 ci, Remove travis and create prow unit-test automation
  .travis.yml
  automation/check-patch.unit-test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#728 [release-0.44] bumper, set components.yaml to track stable branches
  components.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#730 unit-test, Remove copy to artifact in script
  automation/check-patch.unit-test.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#727 bumper, Add a new bumper workflow for release-0.44
  .github/workflows/component-bumper-release-0.44.yml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#733 Release 0.44.1
  Makefile
  README.md
  manifests/cluster-network-addons/0.44.1/cluster-network-addons-operator.0.44.1.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.44.1/namespace.yaml
  manifests/cluster-network-addons/0.44.1/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.44.1/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.44.1/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.44.1.go
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#742 cluster-up, remove NetworkManager installation
  cluster/up.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#740 bumper, fix isPrAlreadyOpened on non master branches
  tools/bumper/cnao_repo_commands.go
  tools/bumper/cnao_repo_commands_test.go
  tools/bumper/component_commands.go
  tools/bumper/git_fakes.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#748 automation, Update CNAO CR to v1 in tier1 setup
  automation/components-functests.setup.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#743 kubemacpool, move to vm opt-out mode
  data/kubemacpool/kubemacpool.yaml
  hack/components/bump-kubemacpool.sh
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XS

#753 Release 0.45.0
  Makefile
  README.md
  manifests/cluster-network-addons/0.45.0/cluster-network-addons-operator.0.45.0.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.45.0/namespace.yaml
  manifests/cluster-network-addons/0.45.0/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.45.0/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.45.0/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.45.0.go
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#754 Check cnao readiness at lifecycle deployment test
  test/e2e/lifecycle/deployment_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#752 Release 0.44.2
  Makefile
  README.md
  manifests/cluster-network-addons/0.44.2/cluster-network-addons-operator.0.44.2.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.44.2/namespace.yaml
  manifests/cluster-network-addons/0.44.2/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.44.2/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.44.2/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/e2e/lifecycle/deployment_test.go
  test/releases/0.44.2.go
  version/description
  version/version.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#762 Add e2e tests custom reporter
  automation/check-patch.e2e-lifecycle-k8s.sh
  automation/check-patch.e2e-workflow-k8s.sh
  automation/check-patch.setup.sh
  test/e2e/lifecycle/main_test.go
  test/e2e/workflow/main_test.go
  test/reporter/reporter.go
  test/reporter/writers.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#764 Build and push multus container to quay.io
  hack/components/bump-multus.sh
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M
