Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2022-05, with the labels that each got.

#1338 Remove trailing spaces from CRD
  pkg/components/components.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1330 Add metrics from data/monitoring/prom-rule.yaml to docs
  data/monitoring/prom-rule.yaml
  docs/metrics.md
  go.mod
  tools/metricsdocs/metricsdocs.go
  tools/metricsdocs/metricsdocs_test.go
Labels: size/L, release-note-none, dco-signoff: yes, lgtm, approved

#1328 e2e/lifecycle, Update tests for stable branches
  automation/check-patch.e2e-lifecycle-k8s.sh
  manifests/cluster-network-addons/0.53.10/cluster-network-addons-operator.0.53.10.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.53.10/namespace.yaml
  manifests/cluster-network-addons/0.53.10/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.53.10/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.53.10/operator.yaml
  manifests/cluster-network-addons/0.58.6/cluster-network-addons-operator.0.58.6.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.58.6/namespace.yaml
  manifests/cluster-network-addons/0.58.6/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.58.6/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.58.6/operator.yaml
  manifests/cluster-network-addons/0.65.6/cluster-network-addons-operator.0.65.6.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.65.6/namespace.yaml
  manifests/cluster-network-addons/0.65.6/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.65.6/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.65.6/operator.yaml
  test/releases/0.53.10.go
  test/releases/0.58.6.go
  test/releases/0.65.6.go
Labels: size/XXL, release-note-none, dco-signoff: yes, lgtm, approved

#1349 gitActions, workflows, Update new branch release-0.76
  .github/workflows/component-bumper.yaml
  .github/workflows/prepare-version.yaml
  .github/workflows/test-release-notes.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1350 [release-0.76] components.yaml, statify components on release-0.76
  components.yaml
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#1302 [release-0.65] Add alert to notify of nmstate removal
  Makefile
  automation/check-patch.e2e-monitoring-k8s.sh
  cluster/up.sh
  data/monitoring/prom-rule.yaml
  go.mod
  go.sum
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/components/components.go
  test/e2e/monitoring/alerts_test.go
  test/e2e/monitoring/main_test.go
  test/e2e/monitoring/prometheus_utils.go
  test/e2e/workflow/deployment_test.go
  test/kubectl/kubectl.go
  test/operations/operations.go
  vendor/github.com/jpillora/backoff/LICENSE
  vendor/github.com/jpillora/backoff/README.md
  vendor/github.com/jpillora/backoff/backoff.go
  vendor/github.com/kevinburke/ssh_config/.travis.yml
  vendor/github.com/kevinburke/ssh_config/AUTHORS.txt
  vendor/github.com/mwitkow/go-conntrack/.gitignore
  vendor/github.com/mwitkow/go-conntrack/.travis.yml
  vendor/github.com/mwitkow/go-conntrack/LICENSE
  vendor/github.com/mwitkow/go-conntrack/README.md
  vendor/github.com/mwitkow/go-conntrack/dialer_reporter.go
  vendor/github.com/mwitkow/go-conntrack/dialer_wrapper.go
  vendor/github.com/mwitkow/go-conntrack/listener_reporter.go
  vendor/github.com/mwitkow/go-conntrack/listener_wrapper.go
  vendor/github.com/prometheus/client_golang/api/client.go
  vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go
  vendor/github.com/prometheus/common/config/config.go
  vendor/github.com/prometheus/common/config/http_config.go
  vendor/golang.org/x/oauth2/clientcredentials/clientcredentials.go
  vendor/modules.txt
Labels: size/XXL, release-note-none, dco-signoff: yes, lgtm, approved

#1322 release-branch, Create a workflow
  .github/workflows/prepare-release-branch.yaml
  Makefile
  hack/update-workflows-branches.sh
Labels: size/L, release-note-none, dco-signoff: yes, lgtm, approved

#1355 workflows, Fix jobs in prepare-release-branch workflow
  .github/workflows/prepare-release-branch.yaml
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#1356 workflows, Fix branch names on peter-evans/create-pull-request
  .github/workflows/prepare-release-branch.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1360 Set Not upgradeable only when KNO is not found
  pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
  pkg/controller/statusmanager/status_manager.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1361 Revert "Set degraded if nmstate is deployed on OCP 4.11 or later
  pkg/controller/statusmanager/status_manager.go
  test/e2e/workflow/recovery_test.go
Labels: size/M, release-note-none, dco-signoff: yes, lgtm, approved

#1362 e2e: nac upgradeable condition for nmstate deployment
  test/check/conditions.go
  test/e2e/workflow/deployment_test.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#1352 oci: Support podman
  Makefile
  README.md
  cluster/cluster.sh
  hack/components/bump-linux-bridge.sh
  hack/components/docker-utils.sh
  hack/components/yaml-utils.sh
  hack/prom-rule-ci/verify-rules.sh
Labels: size/M, release-note-none, dco-signoff: yes, lgtm, approved

#1364 [release-0.65] rbac: Add missing cluster-reader verbs
  data/nmstate/operand/cluster_role.yaml
  hack/components/bump-nmstate.sh
  pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
  pkg/network/cluster-info.go
  pkg/network/nmstate.go
  test/e2e/workflow/deployment_test.go
Labels: size/L, release-note-none, dco-signoff: yes, lgtm, approved

#1332 config, sccs: add required parameters
  data/linux-bridge/001-rbac.yaml
  data/linux-bridge/003-bridge-marker.yaml
  data/multus/001-multus.yaml
  hack/components/bump-bridge-marker.sh
  hack/components/bump-multus.sh
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved
