Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2022-03, with the labels that each got.

#1214 kubevirtci: Bump to k8s-1.23
  README.md
  automation/check-patch.e2e-lifecycle-k8s.sh
  automation/check-patch.e2e-workflow-k8s.sh
  automation/components-functests.setup.sh
  cluster/cluster.sh
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#1247 Annotate NMState CR with rejectOwner annotation
  data/nmstate/operator/nmstate.io_v1_nmstate_cr.yaml
  hack/components/bump-nmstate.sh
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#1231 nmstate: Remove all except API
  Makefile
  README.md
  automation/check-patch.e2e-multus-functests.sh
  automation/check-patch.e2e-nmstate-functests.sh
  automation/components-functests.setup.sh
  components.yaml
  data/nmstate/operand/namespace.yaml
  data/nmstate/operand/nmstate.io_nodenetworkconfigurationenactments.yaml
  data/nmstate/operand/nmstate.io_nodenetworkconfigurationpolicies.yaml
  data/nmstate/operand/nmstate.io_nodenetworkstates.yaml
  data/nmstate/operand/operator.yaml
  data/nmstate/operand/role.yaml
  data/nmstate/operand/role_binding.yaml
  data/nmstate/operand/scc.yaml
  data/nmstate/operand/service_account.yaml
  data/nmstate/operator/nmstate.io_v1_nmstate_cr.yaml
  go.mod
  hack/components/bump-nmstate.sh
  pkg/apply/apply.go
  pkg/components/components.go
  pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
  pkg/controller/networkaddonsconfig/testdata/data.yaml
  pkg/network/cluster-info.go
  pkg/network/network.go
  pkg/network/nmstate.go
  templates/cluster-network-addons/VERSION/cluster-network-addons-operator.VERSION.clusterserviceversion.yaml.in
  test/check/check.go
  test/check/components.go
  test/e2e/workflow/deployment_test.go
  test/e2e/workflow/nmstate_test.go
  test/e2e/workflow/validation_test.go
  test/releases/99.0.0.go
  tools/bumper/parser_test.go
  tools/manifest-templator/manifest-templator.go
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#1251 knmstate: Remove automation and cleanup cluster/up
  automation/check-patch.e2e-nmstate-functests.sh
  cluster/up.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1222 Test new multus features
  automation/check-patch.e2e-multus-functests.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1253 multus: Delete cni cache at preStop
  data/multus/001-multus.yaml
  hack/components/bump-multus.sh
Labels: release-note, size/S, kind/bug, dco-signoff: yes, lgtm, approved

#1255 [release-0.58] Annotate NMState CR with rejectOwner annotation
  data/nmstate/operator/nmstate.io_v1beta1_nmstate_cr.yaml
  hack/components/bump-nmstate.sh
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#1258 kubevirtci_tag, Bump to 2203021427-243853c
  cluster/cluster.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1250 e2e, alerts, Add monitoring lane and tests
  Makefile
  automation/check-patch.e2e-monitoring-k8s.sh
  cluster/up.sh
  go.mod
  go.sum
  pkg/components/components.go
  test/e2e/monitoring/alerts_test.go
  test/e2e/monitoring/main_test.go
  test/e2e/monitoring/prometheus_utils.go
  test/kubectl/kubectl.go
  test/operations/operations.go
  vendor/github.com/jpillora/backoff/LICENSE
  vendor/github.com/jpillora/backoff/README.md
  vendor/github.com/jpillora/backoff/backoff.go
  vendor/github.com/mwitkow/go-conntrack/.gitignore
  vendor/github.com/mwitkow/go-conntrack/.travis.yml
  vendor/github.com/mwitkow/go-conntrack/LICENSE
  vendor/github.com/mwitkow/go-conntrack/README.md
  vendor/github.com/mwitkow/go-conntrack/dialer_reporter.go
  vendor/github.com/mwitkow/go-conntrack/dialer_wrapper.go
  vendor/github.com/mwitkow/go-conntrack/listener_reporter.go
  vendor/github.com/mwitkow/go-conntrack/listener_wrapper.go
  vendor/github.com/prometheus/client_golang/api/client.go
  vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go
  vendor/github.com/prometheus/common/config/config.go
  vendor/github.com/prometheus/common/config/http_config.go
  vendor/golang.org/x/oauth2/clientcredentials/clientcredentials.go
  vendor/modules.txt
Labels: size/XXL, release-note-none, dco-signoff: yes, lgtm, approved

#1257 [release-0.65] Test CNAO creates NMState CR without owner reference
  test/e2e/workflow/deployment_test.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1259 [release-0.65] nmstate: propagate placementConfiguration to NMState CR
  data/nmstate/operator/nmstate.io_v1_nmstate_cr.yaml
  hack/components/bump-nmstate.sh
  pkg/network/nmstate.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#1265 linux-bridge: Move to main branch
  components.yaml
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#1272 DeleteOwnedObject, Change Delete handling log location
  pkg/apply/apply.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1267 [release-0.42] components, fix linux bridge primary branch to main
  components.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, approved

#1268 [release-0.44] components, fix linux bridge primary branch to main
  components.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1271 [release-0.53] components, fix linux bridge primary branch to main
  components.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1264 Add TLS Security Profile API to NAC
  data/kubemacpool/kubemacpool.yaml
  hack/components/bump-kubemacpool.sh
  pkg/apis/networkaddonsoperator/shared/networkaddonsconfig_types.go
  pkg/apis/networkaddonsoperator/shared/zz_generated.deepcopy.go
  pkg/components/components.go
  pkg/network/kubemacpool.go
  pkg/network/tlsSecurityProfile.go
  pkg/network/tlsSecurityProfile_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1227 Add test cases for runbook URLs
  test/e2e/monitoring/alerts_test.go
  test/e2e/monitoring/rules_test.go
Labels: size/M, release-note-none, dco-signoff: yes, lgtm, approved, ok-to-test

#1276 TLS: Move tls env vard to mac-controller-mgr
  data/kubemacpool/kubemacpool.yaml
  hack/components/bump-kubemacpool.sh
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#1281 gitActions, Remove unsupported workflows
  .github/workflows/component-bumper.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1297 [release-0.65] components, Bump ovs-cni to v0.26.1
  components.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#1300 crds: sort tlsProfiles to generate deterministic crd
  pkg/components/components.go
  pkg/components/tlsProfiles.go
  pkg/components/tlsProfiles_test.go
Labels: size/M, dco-signoff: yes, lgtm, approved

#1282 monitoring, e2e, Move endpoints test to monitoring lane
  test/e2e/monitoring/endpoints_test.go
  test/e2e/workflow/deployment_test.go
Labels: size/L, release-note-none, dco-signoff: yes, lgtm, approved

#1305 format, Fix format check
  Makefile
  pkg/controller/statusmanager/status_manager.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1312 tls: Use intermediate TLS profile by default
  pkg/network/tlsSecurityProfile.go
  pkg/network/tlsSecurityProfile_test.go
Labels: release-note, size/XS, kind/bug, dco-signoff: yes, lgtm, approved

#1314 Revert "Merge pull request #1305 from RamLavi/fix_format_check"
  Makefile
  pkg/controller/statusmanager/status_manager.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1316 infra: Bump github-release
  go.mod
  go.sum
  hack/release.sh
  vendor/github.com/github-release/github-release/Gopkg.lock
  vendor/github.com/github-release/github-release/Gopkg.toml
  vendor/github.com/github-release/github-release/Makefile
  vendor/github.com/github-release/github-release/README.md
  vendor/github.com/github-release/github-release/cmd.go
  vendor/github.com/github-release/github-release/github/github.go
  vendor/github.com/github-release/github-release/github/version.go
  vendor/github.com/go-stack/stack/.travis.yml
  vendor/github.com/go-stack/stack/LICENSE.md
  vendor/github.com/go-stack/stack/README.md
  vendor/github.com/go-stack/stack/stack.go
  vendor/github.com/inconshreveable/log15/.mailmap
  vendor/github.com/inconshreveable/log15/.travis.yml
  vendor/github.com/inconshreveable/log15/CONTRIBUTORS
  vendor/github.com/inconshreveable/log15/LICENSE
  vendor/github.com/inconshreveable/log15/README.md
  vendor/github.com/inconshreveable/log15/doc.go
  vendor/github.com/inconshreveable/log15/format.go
  vendor/github.com/inconshreveable/log15/handler.go
  vendor/github.com/inconshreveable/log15/handler_go13.go
  vendor/github.com/inconshreveable/log15/handler_go14.go
  vendor/github.com/inconshreveable/log15/logger.go
  vendor/github.com/inconshreveable/log15/root.go
  vendor/github.com/inconshreveable/log15/syslog.go
  vendor/github.com/kevinburke/rest/.gitignore
  vendor/github.com/kevinburke/rest/.travis.yml
  vendor/github.com/kevinburke/rest/CHANGELOG.md
  vendor/github.com/kevinburke/rest/Makefile
  vendor/github.com/kevinburke/rest/README.md
  vendor/github.com/kevinburke/rest/ctx.go
  vendor/github.com/kevinburke/rest/noctx.go
  vendor/github.com/kevinburke/rest/rest.go
  vendor/github.com/kevinburke/rest/restclient/client.go
  vendor/github.com/kevinburke/rest/restclient/transport.go
  vendor/github.com/kevinburke/rest/resterror/resterror.go
  vendor/modules.txt
Labels: size/XXL, release-note-none, dco-signoff: yes, lgtm, approved

#1317 operator-install, Add info in case of a timeout
  cluster/operator-install.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved
