Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2022-11, with the labels that each got.

#1443 Follow latest CNI plugins releases
  components.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1442 Register dynamic networks controller
  Makefile
  README.md
  automation/check-patch.e2e-multus-dynamic-networks-controller-functests.sh
  automation/components-functests.setup.sh
  components.yaml
  data/multus-dynamic-networks-controller/000-controller.yaml
  hack/components/bump-multus-dynamic-networks.sh
  pkg/apis/networkaddonsoperator/shared/networkaddonsconfig_types.go
  pkg/components/components.go
  pkg/network/multus_dynamic_networks_controller.go
  pkg/network/network.go
  test/releases/99.0.0.go
  tools/manifest-templator/manifest-templator.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1445 multus dynamic networks: validate configuration
  pkg/network/multus_dynamic_networks_controller.go
  pkg/network/multus_dynamic_networks_controller_test.go
  pkg/network/network.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#1441 multus, static policy: do not follow tagged multus versions
  components.yaml
  hack/components/bump-multus.sh
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#1455 Explicitly request "use" verb on SCC
  pkg/components/components.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#1462 multus-v4: set generated config to whatever istio expects
  data/multus/001-multus.yaml
  hack/components/bump-multus.sh
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#1464 Integrate dynamic networks controller deployment tests
  test/check/components.go
  test/e2e/workflow/deployment_test.go
Labels: size/M, release-note-none, dco-signoff: yes, lgtm, approved

#1466 makefile: Add missing component to bump-all target
  Makefile
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1465 nmstate: Remove PDB at operator install
  pkg/network/nmstate.go
  test/e2e/workflow/deployment_test.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#1469 makefile: Generalize bump-all
  Makefile
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved
