Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2022-04, with the labels that each got.

#1280 [release 0.65] bump kubevirtci and k8s 1.23
  README.md
  automation/check-patch.e2e-lifecycle-k8s.sh
  automation/check-patch.e2e-workflow-k8s.sh
  automation/components-functests.setup.sh
  cluster/cluster.sh
  cluster/up.sh
  test/releases/0.42.0.go
  test/releases/0.44.0.go
  test/releases/0.44.3.go
  test/releases/0.47.0.go
  test/releases/0.48.0.go
  test/releases/0.49.0.go
  test/releases/0.50.0.go
  test/releases/0.51.0.go
Labels: size/XL, release-note-none, dco-signoff: yes, lgtm, approved

#1292 Set degraded if nmstate is requested in networkAddonsConfig
  pkg/controller/statusmanager/status_manager.go
  test/e2e/workflow/recovery_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#1324 [release-0.65] nmstate: define Self Sign onfiguration defaults in operator code
  pkg/network/nmstate.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#1323 [release-0.65] Set degraded if nmstate is requested in networkAddonsConfig on OCP 4.11 or later
  pkg/controller/statusmanager/status_manager.go
  test/e2e/workflow/recovery_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#1326 [release-0.65] Propagate selfsign conf
  data/nmstate/operator/nmstate.io_v1_nmstate_cr.yaml
  hack/components/bump-nmstate.sh
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#1298 Add metrics types to CNAO metrics description
  docs/metrics.md
  pkg/monitoring/metrics.go
  tools/metricsdocs/metricsdocs.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved, ok-to-test

#1327 vendor, Bump prometheus/client_golang to v1.11.1
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/modules.txt
Labels: size/L, release-note-none, dco-signoff: yes, lgtm, approved

#1334 Set Upgradeable instead of Available condition when nmstate deployed
  pkg/controller/statusmanager/status_manager.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved
