Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2022-06, with the labels that each got.

#1367 hack/release, Introduce eventually to resource upload
  hack/release.sh
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#1368 [release-0.65] Pin CNAO to bridge-markers stable branch
  components.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1365 Add sanity tests for CNAO alerts
  test/e2e/monitoring/rules_test.go
Labels: size/M, release-note-none, dco-signoff: yes, lgtm, approved, needs-ok-to-test

#1371 Avoid syncing nmstate after migration
  cmd/manager/main.go
  go.mod
  go.sum
  pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
  pkg/network/cluster-info.go
  pkg/network/nmstate.go
  test/e2e/workflow/deployment_test.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/LICENSE
  vendor/github.com/nmstate/kubernetes-nmstate/api/shared/condition_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/shared/nodenetworkconfigurationenactment_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/shared/nodenetworkconfigurationpolicy_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/shared/nodenetworkstate_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/shared/nodenetworkstate_util.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/shared/state_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/shared/zz_generated.deepcopy.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1/groupversion_info.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1/nmstate_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1/nodenetworkconfigurationpolicy_types.go
  vendor/github.com/nmstate/kubernetes-nmstate/api/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#1378 [release-0.58] Remove nmcli 1.34 from cluster-up
  cluster/cluster.sh
  cluster/up.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1374 [release-0.58] Pin bridge-marker to stable branch of 0.9.1
  components.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#1384 [release 0.76] bump prometheus client golang 1.11.1
  go.mod
  go.sum
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/modules.txt
Labels: size/L, release-note-none, dco-signoff: yes, lgtm, approved

#1386 bump-multus, Fix ds location
  hack/components/bump-multus.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved
