Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2022-02, with the labels that each got.

#1158 bumper: Use kubevirt-bot token
  .github/workflows/component-bumper-main.yml
  .github/workflows/component-bumper-release-0.42.yml
  .github/workflows/component-bumper-release-0.44.yml
  .github/workflows/component-bumper-release-0.53.yml
  .github/workflows/component-bumper-release-0.58.yml
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#1167 [release-0.58] cluster: Enable just ovs repo (#1163)
  cluster/up.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1160 bumper: Move github actions to matrix
  .github/workflows/component-bumper-main.yml
  .github/workflows/component-bumper-release-0.42.yml
  .github/workflows/component-bumper-release-0.44.yml
  .github/workflows/component-bumper-release-0.53.yml
  .github/workflows/component-bumper.yaml
Labels: size/L, release-note-none, dco-signoff: yes, lgtm, approved

#1171 actions: Clean up auto bumper
  .github/workflows/component-bumper-release-0.65.yaml
  .github/workflows/component-bumper.yaml
Labels: release-note-none, dco-signoff: yes

#1172 actions: Remove BASE_BRANCH
  .github/workflows/component-bumper.yaml
  pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
Labels: release-note-none, dco-signoff: yes

#1173 actions: Fix autobumper typo
  .github/workflows/component-bumper.yaml
Labels: release-note-none, dco-signoff: yes

#1174 Revert "actions: Remove BASE_BRANCH"
  .github/workflows/component-bumper.yaml
  pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
Labels: release-note-none, dco-signoff: yes

#1175 actions: Remove BASE_BRANCH
  .github/workflows/component-bumper.yaml
  pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
Labels: release-note-none, dco-signoff: yes

#1176 controller: Go back to nmstate-op deployments
  pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
Labels: release-note-none, size/XS, dco-signoff: yes

#1178 bumper: Don't cancel jobs if one fail
  .github/workflows/component-bumper.yaml
Labels: release-note-none, dco-signoff: yes

#1180 bumper: Add github workflow_dispatcher
  .github/workflows/component-bumper.yaml
Labels: release-note-none, dco-signoff: yes

#1181 components: Mark linux-bridge autobumper to static
  components.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1165 [release-0.65] cluster: Enable just ovs repo (#1163)
  cluster/up.sh
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/L, release-note-none, dco-signoff: yes, lgtm, approved

#1187 actions: Prepare versioon from github
  .github/workflows/prepare-version.yaml
Labels: release-note-none, dco-signoff: yes

#1188 actions: Fix prepare version distpatcher
  .github/workflows/prepare-version.yaml
Labels: release-note-none, dco-signoff: yes

#1166 [release-0.53] cluster: Enable just ovs repo (#1163)
  cluster/cluster.sh
  cluster/up.sh
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/L, release-note-none, dco-signoff: yes, lgtm, approved

#1205 [release-0.58] go: Bump to 1.16
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/L, release-note-none, dco-signoff: yes, lgtm, approved

#1145 labels: Do not label operator namespace with unneeded labels
  pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
  pkg/names/names.go
  pkg/network/network.go
  pkg/util/k8s/labels.go
  test/check/check.go
  test/e2e/lifecycle/upgrade_test.go
Labels: size/L, release-note-none, dco-signoff: yes, lgtm, approved

#1207 infra: Use PRs to compose release notes
  Makefile
  RELEASE.md
  hack/prepare-release.sh
  hack/release-notes.tmpl
  hack/release.sh
  hack/render-release-notes.sh
  hack/versions.sh
  version/description
Labels: size/L, release-note-none, dco-signoff: yes, lgtm, approved

#1210 0.65, infra: Use PRs to compose release notes
  Makefile
  RELEASE.md
  hack/prepare-release.sh
  hack/release-notes.tmpl
  hack/release.sh
  hack/render-release-notes.sh
  hack/versions.sh
  version/description
Labels: size/L, release-note-none, dco-signoff: yes, lgtm, approved

#1212 0.58, infra: Use PRs to compose release notes
  Makefile
  RELEASE.md
  hack/prepare-release.sh
  hack/release-notes.tmpl
  hack/release.sh
  hack/render-release-notes.sh
  hack/versions.sh
  version/description
Labels: size/L, release-note-none, dco-signoff: yes, lgtm, approved

#1213 0.53, infra: Use PRs to compose release notes
  Makefile
  RELEASE.md
  hack/prepare-release.sh
  hack/release-notes.tmpl
  hack/release.sh
  hack/render-release-notes.sh
  hack/versions.sh
  version/description
Labels: size/L, release-note-none, dco-signoff: yes, lgtm, approved

#1217 multus: Fix quay.io SHA
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#1216 autobumper: Increase to 100 the commits lookup
  tools/bumper/component_commands.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1221 [0.53] multus: Fix quay.io SHA
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#1220 [0.58] multus: Fix quay.io SHA
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#1233 Fix a typo in KubemacpoolDown runboook url
  data/monitoring/prom-rule.yaml
  hack/prom-rule-ci/prom-rules-tests.yaml
Labels: lgtm, approved

#1235 e2e: test nmstate switch from CNAO to nmstate-operator
  test/e2e/workflow/deployment_test.go
Labels: lgtm, approved

#1237 [release-0.65] e2e: test nmstate switch from CNAO to nmstate-operator
  test/e2e/workflow/deployment_test.go
Labels: size/M, release-note-none, dco-signoff: yes, lgtm, approved

#1238 tests, metrics: Fix potential flakes on metrics scraping test
  test/check/check.go
  test/e2e/workflow/deployment_test.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#1144 metrics: Use https instead of http
  Makefile
  data/kubemacpool/kubemacpool.yaml
  data/monitoring/service.yaml
  data/monitoring/service_monitor.yaml
  hack/components/bump-kubemacpool.sh
  hack/generate-manifests.sh
  pkg/components/components.go
  pkg/network/kubemacpool.go
  test/check/check.go
  test/e2e/workflow/deployment_test.go
  test/kubectl/kubectl.go
  test/releases/99.0.0.go
  test/releases/releases.go
  test/reporter/writers.go
  tools/manifest-templator/manifest-templator.go
Labels: size/L, release-note-none, dco-signoff: yes, lgtm, approved

#1219 multus: Bump to 3.8
  automation/check-patch.e2e-multus-functests.sh
  components.yaml
  data/multus/001-multus.yaml
  hack/components/bump-multus.sh
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved
