Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2022-01, with the labels that each got.

#1128 dockerfile: Use quay.io instead of docker.io
  build/operator/Dockerfile
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1125 Release 0.53.11
  Makefile
  README.md
  manifests/cluster-network-addons/0.53.11/cluster-network-addons-operator.0.53.11.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.53.11/namespace.yaml
  manifests/cluster-network-addons/0.53.11/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.53.11/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.53.11/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.53.11.go
  version/description
  version/version.go
Labels: size/XXL, release-note-none, dco-signoff: yes, lgtm, approved

#1135 Release 0.65.2
  Makefile
  README.md
  manifests/cluster-network-addons/0.65.2/cluster-network-addons-operator.0.65.2.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.65.2/namespace.yaml
  manifests/cluster-network-addons/0.65.2/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.65.2/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.65.2/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.65.2.go
  version/description
  version/version.go
Labels: size/XXL, release-note-none, dco-signoff: yes, lgtm, approved

#1136 Release 0.58.6
  Makefile
  README.md
  manifests/cluster-network-addons/0.58.6/cluster-network-addons-operator.0.58.6.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.58.6/namespace.yaml
  manifests/cluster-network-addons/0.58.6/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.58.6/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.58.6/operator.yaml
  manifests/cluster-network-addons/cluster-network-addons.package.yaml
  test/releases/0.58.6.go
  version/description
  version/version.go
Labels: size/XXL, release-note, dco-signoff: yes, lgtm, approved

#1141 deps: Ping NetworkManager to 1.34
  cluster/up.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1140 knmstate: Reduce the number of e2e tests
  automation/check-patch.e2e-nmstate-functests.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1137 Update list of released versions for upgrade test
  automation/check-patch.e2e-lifecycle-k8s.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1142 Update Dockerfile to use centos:stream9
  build/operator/Dockerfile
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#1148 0.65, components: Follow knmstate release branch
  components.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1149 Revert "0.65, components: Follow knmstate release branch (#1148)"
  components.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1153 components: Mark all of them as tagged
  components.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1151 [release-0.65] components: Follow KMP release branch
  components.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1152 0.65: Mark as static components with main
  components.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1100 Add tool to generate metrics documentation
  Makefile
  automation/check-patch.unit-test.sh
  data/monitoring/prom-rule.yaml
  docs/metrics.md
  hack/diff-csv.sh
  hack/prom-rule-ci/prom-rules-tests.yaml
  pkg/monitoring/metrics.go
  tools/metricsdocs/metricsdocs.go
  tools/metricsdocs/metricsdocs_suite_test.go
  tools/metricsdocs/metricsdocs_test.go
Labels: size/L, release-note-none, dco-signoff: yes, lgtm, approved

#1159 bumper: Add auto bump for release-0.65
  .github/workflows/component-bumper-release-0.65.yaml
Labels: size/M, release-note-none, dco-signoff: yes, lgtm, approved
