Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2023-03, with the labels that each got.

#1515 placement-configuration: Add infra tolerations
  pkg/network/placement_configuration.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#1516 [release-0.85] components: Freeze bumps for stable branch
  components.yaml
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#1519 macvtap: allows overriding the macvtap device plugin configuration
  components.yaml
  data/macvtap/002-macvtap-daemonset.yaml
  pkg/apis/networkaddonsoperator/shared/networkaddonsconfig_types.go
  pkg/components/components.go
  pkg/network/macvtap.go
  pkg/network/macvtap_test.go
  pkg/network/network.go
  test/e2e/workflow/deployment_test.go
Labels: release-note, size/L, dco-signoff: yes, lgtm, approved

#1521 KSD: Bump to v0.0.10
  components.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#1522 ksd: Update bump to include CoreDNS as well
  hack/components/bump-kube-secondary-dns.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved
