Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2023-08, with the labels that each got.

#1592 linux bridge: Fix softlink path
  data/linux-bridge/002-linux-bridge.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1590 macvtap: Block deployment on Openshift
  pkg/network/macvtap.go
  pkg/network/network.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#1595 go modules: Allowlist specific hashicorp modules
  .github/workflows/check_hashicorp_modules.yaml
Labels: size/M, release-note-none, dco-signoff: yes, lgtm, approved

#1594 Improve alert rules sanity test
  test/e2e/monitoring/rules_test.go
Labels: size/M, release-note-none, dco-signoff: yes, lgtm, approved
