Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2023-01, with the labels that each got.

#1494 Add `operator_health_impact` label to CNAO alerts
  data/monitoring/prom-rule.yaml
  hack/prom-rule-ci/prom-rules-tests.yaml
  test/e2e/monitoring/rules_test.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved, ok-to-test

#1499 [ksd] Parameterize "runAsNonRoot" in the yaml
  data/kube-secondary-dns/secondarydns.yaml
  hack/components/bump-kube-secondary-dns.sh
  pkg/network/kube_secondary_dns_controller.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#1501 KSD: Bump to v0.0.9
  components.yaml
  data/kube-secondary-dns/secondarydns.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#1504 Pin goutils to v1.1.1
  go.mod
  go.sum
  vendor/modules.txt
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1505 [release-0.79] Pin goutils to v1.1.1
  go.mod
  go.sum
  vendor/modules.txt
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1506 [release-0.65] Pin goutils to v1.1.1
  go.mod
  go.sum
  vendor/github.com/Masterminds/goutils/cryptorandomstringutils.go
  vendor/github.com/Masterminds/goutils/randomstringutils.go
  vendor/github.com/Masterminds/goutils/stringutils.go
  vendor/modules.txt
Labels: size/M, release-note-none, dco-signoff: yes, lgtm, approved

#1509 Clean up nmstate service if standalone nmstate is installed
  pkg/network/nmstate.go
Labels: size/M, release-note-none, dco-signoff: yes, lgtm, approved
