Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2023-06, with the labels that each got.

#1568 Kubemacpool: Parameterize "runAsNonRoot" in the yaml
  data/kubemacpool/kubemacpool.yaml
  hack/components/bump-kubemacpool.sh
  pkg/network/kubemacpool.go
  pkg/network/network.go
Labels: size/M, release-note-none, dco-signoff: yes, lgtm, approved

#1557 [release-0.79] Bump Bridge CNI to fix VLAN leakage
  components.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved

#1575 Follow tagged bridge CNI releases
  components.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved
