Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2023-09, with the labels that each got.

#1604 arm: Remove amd64 node selector
  pkg/network/placement_configuration.go
  pkg/network/placement_configuration_test.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1607 modules: Amend hashicorp filtering
  .github/workflows/check_hashicorp_modules.yaml
  go.mod
Labels: size/M, release-note-none, dco-signoff: yes, lgtm, approved

#1609 Nominate Or Shoval for the maintainer role
  OWNERS
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1610 release-0.89: bump kube-secondary-dns to v0.0.12
  components.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1613 tools: Fix fmt issues
  tools/metricsdocs/metricsdocs.go
  tools/metricsdocs/metricsdocs_test.go
  tools/prom-metrics-collector/metrics_collector.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1614 check hashicorp: Extract to a file
  .github/workflows/check_hashicorp_modules.yaml
  hack/check_hashicorp.sh
Labels: size/M, release-note-none, dco-signoff: yes, lgtm, approved

#1615 go.mod: Bump go version to 1.19
  go.mod
  pkg/apis/networkaddonsoperator/v1/group_info.go
  pkg/apis/networkaddonsoperator/v1alpha1/group_info.go
  test/e2e/workflow/recovery_test.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved
