Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2023-07, with the labels that each got.

#1582 fix KubemacpoolDown runbook
  data/monitoring/prom-rule.yaml
  hack/prom-rule-ci/prom-rules-tests.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1573 linux bridge: Consolidate CNIs
  data/linux-bridge/002-linux-bridge.yaml
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#1588 Update metric names to fit metrics naming conventions
  data/monitoring/prom-rule.yaml
  docs/metrics.md
  hack/prom-rule-ci/prom-rules-tests.yaml
  tools/prom-metrics-collector/metrics_collector.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved, ok-to-test

#1587 Allow restriction of Multus RBAC
  pkg/components/components.go
  tools/manifest-templator/manifest-templator.go
Labels: size/M, release-note-none, dco-signoff: yes, lgtm, approved
