Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2024-03, with the labels that each got.

#1771 Apply monitoring linter
  Makefile
  automation/check-patch.unit-test.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1774 Update operator-observability version
  docs/metrics.md
  go.mod
  go.sum
  vendor/github.com/machadovilaca/operator-observability/pkg/docs/metrics.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/collector.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/counter.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/counter_vec.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/gauge.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/gauge_vec.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/histogram.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/histogram_vec.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/metric.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/registry.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/summary.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/summary_vec.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatormetrics/wrapper_registry.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/prometheusrules.go
  vendor/github.com/machadovilaca/operator-observability/pkg/operatorrules/registry.go
  vendor/k8s.io/utils/pointer/pointer.go
  vendor/k8s.io/utils/ptr/OWNERS
  vendor/k8s.io/utils/ptr/README.md
  vendor/k8s.io/utils/ptr/ptr.go
  vendor/modules.txt
  vendor/sigs.k8s.io/structured-merge-diff/v4/schema/elements.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/schema/schemaschema.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/typed/merge.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/typed/typed.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/typed/validate.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/mapreflect.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/mapunstructured.go
  vendor/sigs.k8s.io/structured-merge-diff/v4/value/reflectcache.go
Labels: size/XL, release-note-none, dco-signoff: yes, lgtm, approved

#1776 Add operator-observability rules unit test
  go.mod
  go.sum
  pkg/monitoring/rules/rules_suite_test.go
  pkg/monitoring/rules/rules_test.go
  vendor/github.com/grafana/regexp/.gitignore
  vendor/github.com/grafana/regexp/LICENSE
  vendor/github.com/grafana/regexp/README.md
  vendor/github.com/grafana/regexp/backtrack.go
  vendor/github.com/grafana/regexp/exec.go
  vendor/github.com/grafana/regexp/onepass.go
  vendor/github.com/grafana/regexp/regexp.go
  vendor/github.com/machadovilaca/operator-observability/pkg/testutil/alert_custom_validations.go
  vendor/github.com/machadovilaca/operator-observability/pkg/testutil/alert_validation.go
  vendor/github.com/machadovilaca/operator-observability/pkg/testutil/linter.go
  vendor/github.com/machadovilaca/operator-observability/pkg/testutil/problem.go
  vendor/github.com/machadovilaca/operator-observability/pkg/testutil/recording_rule_validation.go
  vendor/modules.txt
Labels: size/XXL, release-note-none, dco-signoff: yes, lgtm, approved
