Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2024-08, with the labels that each got.

#1843 kubevirt: Fix deploying kubevirt on git actions
  .github/workflows/kubevirt-ipam-controller.yaml
  automation/components-functests.setup.sh
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#1841 Add primary UDN net-attach-def
  data/kubevirt-ipam-controller/004-primary-udn-kubevirt-binding-networkattachdef.yaml
  go.mod
  hack/components/bump-kubevirt-ipam-controller.sh
  pkg/components/components.go
  pkg/network/kubevirt_ipam_controller_test.go
  test/check/check.go
  test/check/components.go
  test/e2e/workflow/deployment_test.go
  test/env/env.go
Labels: size/L, release-note-none, dco-signoff: yes, lgtm, approved

#1851 primary-udn: Match NAD type to binary name
  data/kubevirt-ipam-controller/004-primary-udn-kubevirt-binding-networkattachdef.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1852 tests: Fix isKindNotFound
  test/check/check.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1854 Add missing RBACS for kubevirt-ipam-controller
  components.yaml
  data/kubevirt-ipam-controller/001-kubevirtipamcontroller.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: size/M, release-note-none, dco-signoff: yes, lgtm, approved

#1867 git actions, ipam: Run on all branches
  .github/workflows/kubevirt-ipam-controller.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1866 [release-0.95] git actions: Update IPAM lane to run branch
  .github/workflows/kubevirt-ipam-controller.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1869 lifecycle: Update RELEASES_SELECTOR
  README.md
  automation/check-patch.e2e-lifecycle-k8s.sh
  manifests/cluster-network-addons/0.89.3/cluster-network-addons-operator.0.89.3.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.89.3/namespace.yaml
  manifests/cluster-network-addons/0.89.3/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.89.3/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.89.3/operator.yaml
  manifests/cluster-network-addons/0.91.1/cluster-network-addons-operator.0.91.1.clusterserviceversion.yaml
  manifests/cluster-network-addons/0.91.1/namespace.yaml
  manifests/cluster-network-addons/0.91.1/network-addons-config-example.cr.yaml
  manifests/cluster-network-addons/0.91.1/network-addons-config.crd.yaml
  manifests/cluster-network-addons/0.91.1/operator.yaml
  test/releases/0.89.3.go
  test/releases/0.91.1.go
Labels: size/XXL, release-note-none, dco-signoff: yes, lgtm, approved

#1870 lifecycle: Delete non supported releases
  test/releases/0.76.0.go
  test/releases/0.76.3.go
  test/releases/0.77.0.go
  test/releases/0.78.0.go
  test/releases/0.79.0.go
  test/releases/0.79.1.go
  test/releases/0.79.2.go
  test/releases/0.80.0.go
  test/releases/0.81.0.go
  test/releases/0.82.0.go
  test/releases/0.83.0.go
  test/releases/0.83.1.go
  test/releases/0.84.0.go
  test/releases/0.85.0.go
  test/releases/0.85.1.go
  test/releases/0.85.2.go
  test/releases/0.85.3.go
  test/releases/0.86.0.go
  test/releases/0.86.1.go
  test/releases/0.87.0.go
  test/releases/0.88.0.go
Labels: size/XXL, release-note-none, dco-signoff: yes, lgtm, approved

#1868 components/kmp: Follow stable branch
  components.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1872 lifecycle: Add helper script to fetch missing manifests
  hack/update_releases.sh
Labels: size/M, release-note-none, dco-signoff: yes, lgtm, approved

#1876 git actions, ipam: Add logs collecting upon e2e errors
  .github/workflows/kubevirt-ipam-controller.yaml
  .gitignore
  automation/check-patch.e2e-kubevirt-ipam-controller-functests.sh
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#1875 ipam: Reduce git actions noise
  .github/workflows/kubevirt-ipam-controller.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved
