Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2024-01, with the labels that each got.

#1748 Avoid to emit duplicates for enum fileds
  pkg/components/components.go
  pkg/components/components_test.go
  pkg/network/tlsSecurityProfile.go
  pkg/network/tlsSecurityProfile_test.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved, ok-to-test

#1760 [release-0.91] components/kubemacpool: Follow release-0.42 stable branch
  components.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, approved

#1757 Refactor monitoring rules
  Makefile
  data/monitoring/prom-rule.yaml
  docs/metrics.md
  go.mod
  hack/prom-rule-ci/verify-rules.sh
  pkg/components/components.go
  pkg/monitoring/monitoring.go
  pkg/monitoring/rules/alerts/kubemacpool.go
  pkg/monitoring/rules/alerts/operator.go
  pkg/monitoring/rules/alerts/prometheus.go
  pkg/monitoring/rules/recordingrules/kubemacpool.go
  pkg/monitoring/rules/recordingrules/operator.go
  pkg/monitoring/rules/recordingrules/recordingrules.go
  pkg/monitoring/rules/rules.go
  tools/metrics-parser/metrics_parser.go
  tools/metricsdocs/metricsdocs.go
  tools/prom-metrics-collector/metrics_json_generator.go
  tools/prom-rule-ci/prom-rules-tests.yaml
  tools/prom-rule-ci/verify-rules.go
Labels: size/XL, release-note, dco-signoff: yes, lgtm, approved

#1766 go: Update script to install latest go
  hack/install-go.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved
