Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2024-09, with the labels that each got.

#1882 ipam,e2e: Add disableSerialConsoleLog
  automation/check-patch.e2e-kubevirt-ipam-controller-functests.sh
Labels: release-note-none, size/XS, dco-signoff: yes

#1887 bump kubevirt-ipam-controller to v0.1.7-alpha
  automation/check-patch.e2e-kubevirt-ipam-controller-functests.sh
  components.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#1883 ipam: Fix artifacts collecting
  .github/workflows/kubevirt-ipam-controller.yaml
  .gitignore
  automation/check-patch.e2e-kubevirt-ipam-controller-functests.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1888 tools/bumper: Fix latest vtag check
  tools/bumper/cnao_repo_commands.go
  tools/bumper/cnao_repo_commands_test.go
Labels: size/M, release-note-none, dco-signoff: yes, lgtm, approved

#1898 tools/bumper: Allow general vtag format.
  tools/bumper/cnao_repo_commands.go
  tools/bumper/cnao_repo_commands_test.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#1878 fix: dependency in prom-rules-verify make target
  Makefile
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1904 feat: clean task in Makefile
  Makefile
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1908 Bump k8s provider to 1.30
  README.md
  cluster/cluster.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1905 feat: enable download of go client for host arch
  hack/install-go.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved
