Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2025-01, with the labels that each got.

#1966 CVE-2024-45338: Bump golang.org/x/net
  go.mod
  go.sum
  vendor/golang.org/x/net/LICENSE
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/iter.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/config_pre_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/timer.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/net/http2/write.go
  vendor/golang.org/x/net/http2/writesched_priority.go
  vendor/golang.org/x/net/proxy/per_host.go
  vendor/modules.txt
Labels: size/XXL, release-note-none, dco-signoff: yes, lgtm, approved

#1950 Update linux-bridge component commit to plugin v1.5.1
  components.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1968 Add bumper script
  hack/bumper.sh
Labels: size/M, release-note-none, dco-signoff: yes, lgtm, approved

#1942 cluster/cert-manager-install: Wait for deployments to be ready
  cluster/cert-manager-install.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1979 components, multus-dynamic-networks: update_policy to tagged
  components.yaml
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1985 set default platform based on host-architecture for linux bridge build.
  hack/components/bump-linux-bridge.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1983 [Release 0.97] bump multus-dynamic-networks v0.3.6
  components.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#1991 vendor: Pin kubevirt-ipam-controller to v0.2.0
  automation/check-patch.e2e-kubevirt-ipam-controller-functests.sh
  components.yaml
  data/kubevirt-ipam-controller/001-kubevirtipamcontroller.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved
