Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2025-05, with the labels that each got.

#2257 Fix nightly build
  automation/test-nightly-build.sh
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2258 Nightly build: publish the commit file
  automation/test-nightly-build.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2255 [release 0.93] e2e/workflow: Fix race waiting for components
  test/check/check.go
  test/e2e/workflow/deployment_test.go
Labels: size/L, release-note-none, dco-signoff: yes, lgtm, approved

#2254 [release-0.85] Fix vendoring of golang.org/x/tools/cmd/goimports
  .gitignore
  vendor/github.com/go-errors/errors/cover.out
  vendor/golang.org/x/tools/cmd/goimports/doc.go
  vendor/golang.org/x/tools/cmd/goimports/goimports.go
  vendor/golang.org/x/tools/cmd/goimports/goimports_gc.go
  vendor/golang.org/x/tools/cmd/goimports/goimports_not_gc.go
Labels: size/XL, release-note-none, dco-signoff: yes, lgtm, approved

#2262 fix the test-nightly-build.sh script
  automation/test-nightly-build.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2263 Fix the nightly build test
  automation/test-nightly-build.sh
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2265 nightly: login to quay.io
  automation/test-nightly-build.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2264 Set container's TerminationMessagePolicy to FallbackToLogsOnError
  pkg/components/components.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2239 tests: Check for configMap deploy and removal
  test/check/check.go
  test/check/components.go
Labels: size/M, release-note-none, dco-signoff: yes, lgtm, approved, kind/flake

#2279 components: Bump kubemacpool to v0.47.0
  components.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2287 [release-0.99] Follow kubemacpool stable branch
  components.yaml
Labels: release-note-none, size/XS, dco-signoff: yes

#2283 automation/workflow: Pre-install kubevirt
  automation/check-patch.e2e-workflow-k8s.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved, kind/flake

#2288 Fix failure in nightly build
  automation/test-nightly-build.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2302 components,rbac: Grant permissions for r/w network-policies
  pkg/components/components.go
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#2314 tools/bumper: Initiate bump after branch following latest is tagged
  tools/bumper/bumper.go
  tools/bumper/cnao_repo_commands.go
  tools/bumper/cnao_repo_commands_test.go
Labels: size/M, release-note-none, dco-signoff: yes, lgtm, approved

#2322 Move the nightly build images to quay.io/kubevirt
  automation/test-nightly-build.sh
Labels: release-note, size/XS, dco-signoff: yes, lgtm, approved
