Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2025-06, with the labels that each got.

#2342 Consume and install kube-seconday-dns network-policy
  data/kube-secondary-dns/secondarydns.yaml
  hack/components/bump-kube-secondary-dns.sh
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#2341 Opt-in for network-policies provided by hco-bundle for CNAO and its components pods
  data/kube-secondary-dns/secondarydns.yaml
  data/kubemacpool/kubemacpool.yaml
  data/kubevirt-ipam-controller/001-kubevirtipamcontroller.yaml
  hack/components/bump-kube-secondary-dns.sh
  hack/components/bump-kubemacpool.sh
  hack/components/bump-kubevirt-ipam-controller.sh
  pkg/components/components.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#2331 Linux bridge: Harden SCC by restricting SELinux context and allowed volume types
  data/linux-bridge/001-rbac.yaml
  data/linux-bridge/002-linux-bridge.yaml
Labels: release-note, size/S, dco-signoff: yes, lgtm, approved

#2348 CI: Add test coverage for network-policies by simulate network restrictions
  automation/check-patch.e2e-kube-secondary-dns-functests.sh
  automation/check-patch.e2e-kubemacpool-functests.sh
  automation/check-patch.e2e-kubevirt-ipam-controller-functests.sh
  automation/check-patch.e2e-monitoring-k8s.sh
  automation/check-patch.e2e-workflow-k8s.sh
  hack/install-network-policy.sh
Labels: size/L, release-note-none, dco-signoff: yes, lgtm, approved
