Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2025-02, with the labels that each got.

#1931 Use OpenShift's required-scc annotation on components
  data/kube-secondary-dns/secondarydns.yaml
  data/kubemacpool/kubemacpool.yaml
  data/kubevirt-ipam-controller/001-kubevirtipamcontroller.yaml
  data/kubevirt-ipam-controller/003-passtbindingcni.yaml
  data/linux-bridge/002-linux-bridge.yaml
  data/linux-bridge/003-bridge-marker.yaml
  hack/components/bump-bridge-marker.sh
  hack/components/bump-kube-secondary-dns.sh
  hack/components/bump-kubemacpool.sh
  hack/components/bump-kubevirt-ipam-controller.sh
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved

#1995 vendor: Pin ovs-cni to v0.38.0
  components.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#1978 tools/bumper: Refactor using DeferCleanup
  tools/bumper/cnao_repo_commands_test.go
  tools/bumper/component_commands_test.go
Labels: size/M, release-note-none, dco-signoff: yes, lgtm, approved

#2002 [release-0.97] Revert "vendor: Pin ovs-cni to v0.38.0 (#1995)"
  components.yaml
  pkg/components/components.go
  test/releases/99.0.0.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2007 Upgrade monitoring linter to latest
  Makefile
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2009 Align placement with HCO components
  data/kubevirt-ipam-controller/003-passtbindingcni.yaml
  hack/components/bump-kubevirt-ipam-controller.sh
  pkg/network/kube_secondary_dns_controller.go
  pkg/network/kubevirt_ipam_controller.go
  pkg/network/kubevirt_ipam_controller_test.go
  pkg/network/placement_configuration.go
Labels: release-note, size/M, dco-signoff: yes, lgtm, approved
