Repository kubevirt/cluster-network-addons-operator, pull requests merged in 2025-04, with the labels that each got.

#2214 [release-0.89] e2e, lifecycle: Remove old unsupported releases upgrade
  test/releases/0.65.0.go
  test/releases/0.65.1.go
  test/releases/0.65.2.go
  test/releases/0.65.6.go
  test/releases/0.66.0.go
  test/releases/0.67.0.go
  test/releases/0.68.0.go
  test/releases/0.69.0.go
  test/releases/0.70.0.go
  test/releases/0.71.0.go
  test/releases/0.72.0.go
  test/releases/0.73.0.go
  test/releases/0.74.0.go
  test/releases/0.75.0.go
  test/releases/0.77.0.go
  test/releases/0.78.0.go
Labels: size/XXL, release-note-none, dco-signoff: yes, lgtm, approved

#2212 Bump kubevirtci to use a tag with multi-architecture support
  cluster/cluster.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2220 [release-0.97] Makefile: Enforce max allowed version
  Makefile
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2225 [release-0.93] makefile: Introduce go version enforcement
  Makefile
  go.mod
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2223 [release-0.95] makefile: Fix max go version enforcement
  Makefile
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2222 Makefile: Enforce max allowed version
  Makefile
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2226 [release-0.91] makefile: Introduce go version enforcement
  Makefile
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2227 [release-0.89] makefile: Introduce go version enforcement
  Makefile
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2228 [release-0.79] makefile: Introduce go version enforcement
  Makefile
  go.mod
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2217 gitActions: Add workflow to bump kubevirtci
  .github/workflows/kubevirtci-bumper.yaml
Labels: size/M, release-note-none, dco-signoff: yes, lgtm, approved

#2230 e2e, reporter: Enhance debugging logs
  test/reporter/reporter.go
  test/reporter/writers.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2216 automation: Add workflow nightly script
  automation/test-nightly-build.sh
Labels: size/M, release-note-none, dco-signoff: yes, lgtm, approved

#2241 pkg: Handle unhandled errors
  pkg/apply/merge.go
  pkg/apply/merge_test.go
  pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
Labels: release-note-none, size/S, dco-signoff: yes, lgtm, approved

#2242 pkg/util/k8s: remove unused DynamicRESTMapper code
  pkg/util/k8s/dynamicrestmapper.go
Labels: size/L, release-note-none, dco-signoff: yes, lgtm, approved, kind/cleanup

#2243 Fix vendoring of golang.org/x/tools/cmd/goimports
  .gitignore
  tools/vendor/golang.org/x/tools/cmd/goimports/doc.go
  tools/vendor/golang.org/x/tools/cmd/goimports/goimports.go
  tools/vendor/golang.org/x/tools/cmd/goimports/goimports_gc.go
  tools/vendor/golang.org/x/tools/cmd/goimports/goimports_not_gc.go
  vendor/golang.org/x/tools/cmd/goimports/doc.go
  vendor/golang.org/x/tools/cmd/goimports/goimports.go
  vendor/golang.org/x/tools/cmd/goimports/goimports_gc.go
  vendor/golang.org/x/tools/cmd/goimports/goimports_not_gc.go
Labels: size/XL, release-note-none, dco-signoff: yes, lgtm, approved

#2244 Fix the nightly build
  automation/test-nightly-build.sh
Labels: release-note-none, size/XS, dco-signoff: yes, lgtm, approved

#2245 [release-0.97] Fix vendoring of golang.org/x/tools/cmd/goimports
  .gitignore
  vendor/golang.org/x/tools/cmd/goimports/doc.go
  vendor/golang.org/x/tools/cmd/goimports/goimports.go
  vendor/golang.org/x/tools/cmd/goimports/goimports_gc.go
  vendor/golang.org/x/tools/cmd/goimports/goimports_not_gc.go
Labels: size/XL, release-note-none, dco-signoff: yes, lgtm, approved

#2246 [release-0.95] Fix vendoring of golang.org/x/tools/cmd/goimports
  .gitignore
  vendor/golang.org/x/tools/cmd/goimports/doc.go
  vendor/golang.org/x/tools/cmd/goimports/goimports.go
  vendor/golang.org/x/tools/cmd/goimports/goimports_gc.go
  vendor/golang.org/x/tools/cmd/goimports/goimports_not_gc.go
Labels: size/XL, release-note-none, dco-signoff: yes, lgtm, approved

#2249 [release-0.89] Fix vendoring of golang.org/x/tools/cmd/goimports
  .gitignore
  vendor/github.com/go-errors/errors/cover.out
  vendor/golang.org/x/tools/cmd/goimports/doc.go
  vendor/golang.org/x/tools/cmd/goimports/goimports.go
  vendor/golang.org/x/tools/cmd/goimports/goimports_gc.go
  vendor/golang.org/x/tools/cmd/goimports/goimports_not_gc.go
Labels: size/XL, release-note-none, dco-signoff: yes, lgtm, approved

#2250 [release-0.79] Fix vendoring of golang.org/x/tools/cmd/goimports
  .gitignore
  vendor/github.com/go-errors/errors/cover.out
  vendor/golang.org/x/tools/cmd/goimports/doc.go
  vendor/golang.org/x/tools/cmd/goimports/goimports.go
  vendor/golang.org/x/tools/cmd/goimports/goimports_gc.go
  vendor/golang.org/x/tools/cmd/goimports/goimports_not_gc.go
Labels: size/XL, release-note-none, dco-signoff: yes, lgtm, approved

#2248 [release-0.91] Fix vendoring of golang.org/x/tools/cmd/goimports
  .gitignore
  vendor/golang.org/x/tools/cmd/goimports/doc.go
  vendor/golang.org/x/tools/cmd/goimports/goimports.go
  vendor/golang.org/x/tools/cmd/goimports/goimports_gc.go
  vendor/golang.org/x/tools/cmd/goimports/goimports_not_gc.go
Labels: size/XL, release-note-none, dco-signoff: yes, lgtm, approved

#2247 [release-0.93] Fix vendoring of golang.org/x/tools/cmd/goimports
  .gitignore
  vendor/golang.org/x/tools/cmd/goimports/doc.go
  vendor/golang.org/x/tools/cmd/goimports/goimports.go
  vendor/golang.org/x/tools/cmd/goimports/goimports_gc.go
  vendor/golang.org/x/tools/cmd/goimports/goimports_not_gc.go
Labels: size/XL, release-note-none, dco-signoff: yes, lgtm, approved
